### ISSUE TITLE
Write content for November 2019 Question: Allow for Alternative Initiative Signatures for Persons with Disabilities Amendment

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#10]
https://ballotpedia.org/Maine_Allow_for_Alternative_Initiative_Signatures_for_Persons_with_Disabilities_Amendment_(2019)

**Comment by shannonmcharg** [comment]
# Question title

# Description (will display on homepage)

# The gist

# Ballot question (exact text of the question)

# Yes means

# No means

# Tell me more

# Follow the money

## The money will be used to

## The money will be coming from

# Pros

# Cons

# Who cares

## Support

## Opposition

# Further reading

# References

# Tags

# Election date

**Comment by elburnett** [comment]
Testing if this works

**Comment by shannonmcharg** [comment]
Testing again

**Comment by shannonmcharg** [comment]
@elburnett I fleshed out the template a little bit more and added the link to the full text of the question.  It doesn't post edits to comments to Slack, so if you want people to know you've made edits that are ready to review, add a comment letting us know you made edits.

Can you also keep in mind things it would be helpful to add to the template for future questions as you're filling it out?

**Comment by shannonmcharg** [comment]
We need to get this content written.  Last year, people starting coming to the website in September.  I have time to get it started today.

**Comment by shannonmcharg** [comment]
Draft content is in the issue description.  Does anyone have time to review?

**Comment by shannonmcharg** [comment]
Here it is on the site.  I'd still like to get some other eyeballs on this, so let me know if you have any feedback.
https://maineballot.org/november%202019%20election/Q1_AltSignature/

**Comment by shannonmcharg** [comment]
The new bond issue is now question 1, so this one needs to become question 2.
