### ISSUE TITLE
Write content for Portland July charter question

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#103]
@elburnett Do you have details for this?

# Question title
_Short title describing the question_

# Description (will display on homepage)

# The gist
This resolution would... _Concise summary of the purpose of the question_

# Ballot question (exact text of the question)

# Yes means
I am in favor of _whatever the question does_

# No means
I don't want to _whatever the question does_

# Tell me more
_More details go here_

# Follow the money

The money will be used to
* 

The money will be coming from
* 

# Pros
The primary arguments for this referendum are:
* 

# Cons
The primary arguments against this referendum are:
* 

# Who cares

Support
*

Opposition
*

# Further reading
[Full text](link goes here)
[Ballotpedia article](link goes here)

# References
_Put the number in brackets above to indicate a footnote to a reference._
1. Maine State Legislature. [title of full text](link goes here). Accessed [date].
2. Ballotpedia State Desk. [title of Ballotpedia article](link goes here). Ballotpedia. Accessed [date].

# Image
_Find an open source image that will work for the thumbnail and hero image and put the link to that here._

# Tags

# Election date

**Comment by elburnett** [comment]
I will add the picture to the Slack channel (not seeing how to attach here?) But the wording is:
"Shall a Charter Commission be established for the purpose of revisiting the Municipal Charter?" Yes / No

**Comment by elburnett** [comment]
Question B:

Do you favor approving the Portland School Budget for the upcoming School year that was adopted at the latest City Council Budget meeting?

**Comment by shannonmcharg** [comment]
You can drag and drop a file to attach it here.

**Comment by elburnett** [comment]
![QuestionA](https://user-images.githubusercontent.com/3193746/85039610-eaeda200-b155-11ea-896a-88d1c5f34ac5.jpg)
![QuestionB](https://user-images.githubusercontent.com/3193746/85039624-ecb76580-b155-11ea-8f37-086fec3652fc.jpg)

**Comment by shannonmcharg** [comment]
@elburnett Do you have any more information other than the question text?  If not, maybe we should just include the pictures as a sample ballot like we did for Durham.
