### ISSUE TITLE
Make sample ballots accessible

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#110]
Requires someone who has Acrobat Pro or some tool that can do text recognition.

**Comment by shannonmcharg** [comment]
PDFs of ballots are here: https://github.com/OpenMaine/maineballot/tree/master/assets/docs/2020-07-14_ballots

**Comment by cristoslc** [comment]
I can try running these through ocrmypdf on my machine tomorrow.

**Comment by shannonmcharg** [comment]
@cristoslc Awesome, thanks!

**Comment by shannonmcharg** [comment]
We have two more ballots.  I haven't put the Sample watermark on these yet.  @cristoslc let me know if you need the versions of the other ones without that to get the OCR to work (not sure which should come first).
[Biddeford.pdf](https://github.com/OpenMaine/maineballot/files/4825909/Biddeford.pdf)
[SouthPortland.pdf](https://github.com/OpenMaine/maineballot/files/4825912/SouthPortland.pdf)

**Comment by cristoslc** [comment]
@shannonmcharg I'm testing OCR on the watermarked ones now, will know in a few minutes.

Separately, is there a reason to use the photo of the Portland ballot instead of the official sample from https://portlandmaine.gov/DocumentCenter/View/17946/Sample-Ballots-July-2020?bidId= ?

**Comment by shannonmcharg** [comment]
Nope, we can use the official one.  I couldn't find it when I last looked.

**Comment by cristoslc** [comment]
first result looks pretty promising. I'll grab the Portland official ballot and batch the rest of these.

I'm not familiar with accessibility testing, what should I use to validate that the output is acceptable? Or is any level of OCR with intact words/sentences acceptable?

[Westbrook.ocr.pdf.txt](https://github.com/OpenMaine/maineballot/files/4826083/Westbrook.ocr.pdf.txt)
[Westbrook.ocr.pdf](https://github.com/OpenMaine/maineballot/files/4826082/Westbrook.ocr.pdf)

**Comment by shannonmcharg** [comment]
@rentry What do you do to validate accessibility of pdfs?

**Comment by rentry** [comment]
I don't have a great way to validate. Acrobat will show the rendered output and flag words where the rendering of the text was potentially incorrect. The only other way I've done it is to copy the rendered OCR text into another doc and manually compare with the original.

**Comment by cristoslc** [comment]
I submitted a PR with the updated files. I included the text exports as separate files, in case they can be used somehow. Scanning those will also show the quality of the OCR. The bulk of the text is fine, but there are a ton of artifacts from signatures, glyphs, etc.

If you're expecting a few hundred PDFs, and the output quality is acceptable, we can potentially scale this to an automated service (user uploads the PDF, server runs OCR and commits to a branch).

**Comment by cristoslc** [comment]
The source file for Gardiner didn't OCR well, do you want to keep this issue open or create a new one to try and get a better file?

**Comment by shannonmcharg** [comment]
I'm not going to be able to get a new Gardiner file.  The person I got it from already filled in their ballot.  I did have to lighten the image, so you could try using the original picture and see if it's better.
![Resized_20200620_212224 (1)](https://user-images.githubusercontent.com/12865238/85610116-b29e0600-b624-11ea-9e04-7a19f599b7a6.jpeg)

**Comment by shannonmcharg** [comment]
I don't suspect we'll end up with all that many pdfs.

**Comment by cristoslc** [comment]
Thanks for the additional image! I got slightly better results using the original Gardiner image provided (published 65c3651), but I think it would still give a screen reader fits.

Also added Lewiston.

**Comment by shannonmcharg** [comment]
I added the sample watermark to all the ones that didn't have it.  I'm not sure if that's necessary, especially if the towns that have ballots aren't doing it.  I just wouldn't want anyone to try printing any ballots out and trying to vote with them.  Is that overkill?

**Comment by cristoslc** [comment]
@shannonmcharg I don't see the harm in adding the watermark. I can add watermarking to the process pretty easily, if you want to post the image/pdf overlay you're using.

Is there somewhere it would be useful to document my process, so that others can also perform the OCR conversion? It's just a shell script that runs a few free command line utilities. (Running on a Mac, but I don't know that they're mac-only necessarily.)

**Comment by shannonmcharg** [comment]
I'm just using the watermark function in the Pages menu in my pdf editor.  I pick a gray that shows up with 45 degree angle and 50% opacity.
![image](https://user-images.githubusercontent.com/12865238/85647078-a4270d00-b66b-11ea-93ba-8117d148ba61.png)

Fee free to find a place that makes sense in the wiki to document the OCR process.

**Comment by rentry** [comment]
@shannonmcharg It looks like (from ☝️) that you have the feature to output accessible, searchable PDFs. On the right side, where it reads "Text Recognition," it should allow you to render the text. You'll probably need to do some correction, but it looks like it's there.

**Comment by cristoslc** [comment]
I don't have privileges to edit the wiki, and AFAIK there's no way to do pull requests on a wiki. How would you like me to submit the updates?

**Comment by shannonmcharg** [comment]
Here's Topsham.
![Topsham](https://user-images.githubusercontent.com/12865238/85727763-47f0d700-b6c5-11ea-89cb-93380c8e102a.jpg)

**Comment by shannonmcharg** [comment]
@cristoslc You weren't a member of the OpenMaine organization, which may be why you couldn't edit the wiki.  I sent to an invite to the org, so you should be able to edit after accepting.

**Comment by shannonmcharg** [comment]
@rentry Good to know I have the text recognition capability.  Thanks.

**Comment by cristoslc** [comment]
thanks, @shannonmcharg 

wik updated: https://github.com/OpenMaine/maineballot/wiki/Make-PDFs-screen-reader-friendly-with-OCR

Topsham OCRd and watermarked: 1776d70

**Comment by shannonmcharg** [comment]
@cristoslc The instructions for making the pdfs accessible look great!
