### ISSUE TITLE
Add new election date to website

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#13]
The election is on November 5, 2019.

**Comment by shannonmcharg** [comment]
Test comment

**Comment by congdon** [comment]
Test for Emma, as if I were tasking her to do something. Does she get email? (If not, does she maybe need to turn GitHub notifications on?)

**Comment by shannonmcharg** [comment]
You probably have to @ Emma for her to get email, unless she has it set to get notifications for anything in the repo.

**Comment by shannonmcharg** [comment]
Figured out how to get comments into Slack!

**Comment by congdon** [comment]
Maybe there is a lag, but I'm seeing your comments on the Slack and not mine.

**Comment by shannonmcharg** [comment]
Done
