### ISSUE TITLE
Research getting to a single candidates file for the November election

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#136]
File from the primary: https://docs.google.com/spreadsheets/d/14RapVz5_AlGRza-MsSzzu6cOQRIX_oSu-mcNQy8ytyo/edit#gid=0

Files available for November: https://www.maine.gov/sos/cec/elec/upcoming/index.html

Candidates page from the primary: https://maineballot.org/candidates

**Comment by curtisk** [comment]
Thanks for the reference links, I'll dive in

**Comment by shannonmcharg** [comment]
Thank you!

**Comment by curtisk** [comment]
Spot checking, but it looks like they updated this page 
https://www.maine.gov/sos/cec/elec/upcoming/index.html

with a November candidate list updated a few days ago
https://www.maine.gov/sos/cec/elec/upcoming/gencand20.xlsx

465 down to 440

**Comment by shannonmcharg** [comment]
@curtisk Awesome!

**Comment by shannonmcharg** [comment]
Next week, I'm going to look into pulling this into the file with candidate websites I did for the primary and see how much work it would be to do a page for November.

**Comment by curtisk** [comment]
I think I created a new tab on that sheet for November, was planning on getting back to merging the details

**Comment by shannonmcharg** [comment]
@curtisk I updated the November tab with the Sept 15 updated file and added columns for whether the race is contested or RCV.  I tried to do a match function to get it to pull in the websites from the July tab, but it does work.  Do you know how to do that?

**Comment by curtisk** [comment]
yeah, I usually do a VLOOKUP for stuff like that, but that's where I left off, I can take a look
