### ISSUE TITLE
Write content for November ballot question: Ranked choice voting

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#137]
Looks like RCV is going on the ballot again.  The Secretary of State's office has yet to post the final question, but here's what I know so far.
https://ballotpedia.org/Maine_Ranked-Choice_Voting_for_Presidential_Elections_Referendum_(2020)

# Status of this question
This question may or may not actually appear on the November ballot. The Secretary of State's office is [appealing the decision](https://www.pressherald.com/2020/08/28/maine-secretary-of-state-appeals-judges-ruling-on-ranked-choice-voting/) requiring the question to go on the ballot. If this question goes on the ballot, ranked-choice voting will not be allowed for the presidential election.  If it doesn't go on the ballot, ranked-choice voting will be allowed for the presidential election.

# Question title
Ranked-Choice Voting

# Description (will display on homepage)
This measure would enact ranked-choice voting for presidential elections.

# The gist
Ever wanted a third party or independent candidate to win an election? If this referendum passes, it would be even more possible than it was when voters voted for it in the November 2016 and June 2018 referendum elections.

# Ballot question (exact text of the question)
"Do you want to reject a new law that would require presidential elections in Maine to be decided using ranked-choice voting?"[2]
# Yes means
I want to keep presidential elections the way they are.

# No means
I want presidential elections to use ranked-choice voting.

# Tell me more
Think you’ve seen this question before? You have.

Here's the history:
* After ranked-choice voting was approved by voters in both the [November 2016](https://maineballot.org/november%202016%20election/Q5_RankedChoiceVoting/) and [June 2018](https://maineballot.org/june%202018%20election/Q1_RankedChoiceVoting/) elections, the state legislature enacted a law allowing ranked-choice voting for presidential elections.[4]
* Some people rejected the new law and there is disagreement over whether all of the signatures they collected are valid. [4]
* On August 24, 2020, a judge ruled that the signatures were valid. [2]
* The Secretary of State is currently appealing the decision. [3]

# Follow the money

See [2016 referendum question](https://maineballot.org/november%202016%20election/Q5_RankedChoiceVoting/) for cost estimates.

The money will be used to:
* Print additional ballot pages, oversee the process, and pay overtime and fuel costs to secure and return election ballots

The money will be coming from
* Budget appropriations

# Pros
The primary arguments for this referendum are:
* It costs more money than the current system.
* It takes more time to count ballots.
* Voters could be confused by a more complex ballot.
* Some believe it doesn’t reflect the will of the voters.

# Cons
The primary arguments against this referendum are:
* It enforces the will of the voter and sets a precedent to encourage legislators to carry out the will of the voter for future referendum questions.
* It would support third party and independent candidates.
* It allows voters to vote for their preferred candidate without fear of the spoiler effect.
* It could reduce negative attack ads.
* It is less costly than runoff elections.

# Who cares

Since there isn't an official question yet, there's no registered support or opposition. 

Support
*

Opposition
*

# Further reading
[Full text](link goes here) - TBD once the state actually posts the question
[Maine Ranked-Choice Voting for Presidential Elections Referendum (2020)](https://ballotpedia.org/Maine_Ranked-Choice_Voting_for_Presidential_Elections_Referendum_(2020))

# References
_Put the number in brackets above to indicate a footnote to a reference._
1. Maine State Legislature. [title of full text](link goes here). Accessed [date]. - TBD once the state actually posts the question
2. Ballotpedia State Desk. [Maine Ranked-Choice Voting for Presidential Elections Referendum (2020)](https://ballotpedia.org/Maine_Ranked-Choice_Voting_for_Presidential_Elections_Referendum_(2020)). Ballotpedia. Accessed September 3, 2020.
3. Overton, Penelope. [Maine secretary of state appeals judge’s ruling on ranked-choice voting](https://www.pressherald.com/2020/08/28/maine-secretary-of-state-appeals-judges-ruling-on-ranked-choice-voting/). Portland Press Herald. Accessed September 3, 2020.
4. Thistle, Scott. [State’s high court hears case on people’s veto for ranked choice voting](https://www.pressherald.com/2020/09/03/states-high-court-hears-case-on-peoples-veto-for-ranked-choice-voting/)

# Image
Same image as previous ranked-choice voting questions.

# Tags
Ranked-Choice, Veto Referendum

# Election date
November 3, 2020

**Comment by shannonmcharg** [comment]
Content from the two previous times it was on the ballot:
https://maineballot.org/november%202016%20election/Q5_RankedChoiceVoting/
https://maineballot.org/june%202018%20election/Q1_RankedChoiceVoting/

**Comment by shannonmcharg** [comment]
Looks like the RCV question is still in flux and we may not get sample ballots until the last minute because of the appeal.
https://www.pressherald.com/2020/08/28/maine-secretary-of-state-appeals-judges-ruling-on-ranked-choice-voting/

**Comment by inomyabcs** [comment]
Should the pros and cons be flipped? The primary purpose of the referendum is more for the cons area. Would renaming those headers to "Yes Arguments" and "No Arguments" help?

**Comment by shannonmcharg** [comment]
@inomyabcs Good catch!  I copied and pasted from the previous question, which was flipped.
