### ISSUE TITLE
Review local websites for sample ballots (in October)

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#161]
Ones that are likely to have updated content are marked as "Check back later" in the "Reviewed for Nov column".

Spreadsheet:
https://docs.google.com/spreadsheets/d/1dk58MD0qBAM37BDOZwKIz10hp5AARAIX8u_qvuDnYaI/edit#gid=0

**Comment by JohnBrooking** [comment]
I just updated the spreadsheet's "Ballot link" and "Ballot link text" columns with the link and text for Westbrook's municipal ballot. We have two proposed City Charter amendments.

**Comment by shannonmcharg** [comment]
I went through the list this morning and found a few with updates.  Will have to check back again in a few days.
