### ISSUE TITLE
Make November sample ballots accessible

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#181]
@cristoslc Can you look at the ones for Brunswick, Gardiner, and Topsham?  I attempted to do text recognition, but I don't think it worked right.

**Comment by cristoslc** [comment]
@shannonmcharg I only see Brunswick and Gardiner in the `maineballot/assets/docs/2020-11-03_ballots/` path -- is Topsham committed to the repo?

**Comment by shannonmcharg** [comment]
It’s in a PR that hasn’t been merged yet.

**Comment by shannonmcharg** [comment]
It’s merged now.

**Comment by cristoslc** [comment]
the column layout on these ballots looks like it might be confusing the OCR engine a bit. There's not much we can do, without switching to tools that require drawing the specific text area boxes on each block manually (or writing an ML process that would do the same). I think this is the best we can currently do with this type of generalized solution for now.

If the accessibility is that big a deal, I can see if someone has an existing ML project whose pipeline we can adapt.
