### ISSUE TITLE
Links to sample ballot files are broken on the archived local elections page

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#182]
https://maineballot.org/local-archive/local-2020-07/

They use a relative path that changes when archiving the page. Is there an automated way to update this?

**Comment by curtisk** [comment]
I noticed they are a mixed bag, some I see the issue you are referring to where "assets" is nested under archive, some have links back to the towns' site....and a few of these are 404's at this point. Why were some pulled from town site and uploaded to our assets folder and some not? Should we be archiving the sample ballots, if the towns/cities aren't even doing this?

**Comment by shannonmcharg** [comment]
@curtisk The ones in the assets folder are scanned absentee ballots that aren’t available on the town websites.
