### ISSUE TITLE
Update local election info - Cumberland County

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#194]
Spreadsheet: https://docs.google.com/spreadsheets/d/1dk58MD0qBAM37BDOZwKIz10hp5AARAIX8u_qvuDnYaI/edit#gid=0
Instructions: https://github.com/OpenMaine/maineballot/wiki/Updating-Maine-Ballot-for-an-upcoming-election

**Comment by caitlinpmarshall** [comment]
Cumberland County finished out in the spreadsheet.  Town meetings NOT on June 8 are noted in the "June 2021 ballot" column. (Info not yet copied over to local.csv)
