### ISSUE TITLE
Update local election info - York County

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#209]
Spreadsheet: https://docs.google.com/spreadsheets/d/1dk58MD0qBAM37BDOZwKIz10hp5AARAIX8u_qvuDnYaI/edit#gid=0
Instructions: https://github.com/OpenMaine/maineballot/wiki/Updating-Maine-Ballot-for-an-upcoming-election

**Comment by caitlinpmarshall** [comment]
Updated info and links for remaining York County towns on the spreadsheet. All updates are still in the Google Spreadsheet (I did not transfer into the local.csv document).

Additionally, still need to update dates for towns with town meetings other than June 8:
Buxton - Saturday, June 12
Parsonsfield - school budget meeting was May 18
Shapleigh - town meetins was March 12
York - budget and special referendum was May 22

**Comment by shannonmcharg** [comment]
@caitlinpmarshall Thank you!
