### ISSUE TITLE
Question 1: Electric Transmission Line

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#221]
# Question title
Electric Transmission Line

# Description (will display on homepage)
This measure would halt construction of the New England Clean Energy Connect (NECEC) and require a 2/3 majority to approve similar projects back as far as 2014.

# The gist
This citizen's initiative would prevent the New England Clean Energy Connect (NECEC) from transmitting power from hydroelectric plants in Quebec for use in Maine and Massachusetts. This requires changing the law retroactively, meaning it changes how much of the legislature is needed to approve a project back as far as 2014.

# Ballot question (exact text of the question)
Do you want to ban the construction of high-impact electric transmission lines in the Upper Kennebec Region and to require the Legislature to approve all other such projects anywhere in Maine, both retroactively to 2020, and to require the Legislature, retroactively to 2014, to approve by a two-thirds vote such projects using public land?

# Yes means
I don't want NECEC to construct a high-impact electric transmission line in the Upper Kennebec region and require a 2/3 majority vote for similar projects retroactively to 2020 for projects anywhere in Maine and 2014 for projects on public land.

# No means
I want to allow the NECEC to continue construction of the high-impact electric transmission line in the Upper Kennebec region and I want the legislative rules for approval of such projects to stay the way they are.

# Tell me more
This bill would do 6 things [3]:

1. Require a supermajority of 2/3 approval for a broader definition of high-impact electric transmission lines and to make this provision retroactive back to September 2014.
2. Amend the definition of "high-impact electric transmission line" by removing the exclusions for lines located within energy infrastructure corridors.
3. Modify the requirement for the Public Utilities Commission to no longer require they follow an expired law governing energy infrastructure corridors.
4. Require legislative approval for high-impact electric transmission lines anywhere in Maine with a 2/3 supermajority for those on public lands.
5. Ban construction of high-impact electric transmission lines in the Upper Kennebec Region.
6. Make the legislative approval and construction ban retroactive back to September 2020.

New England Clean Energy Connect (NECEC) corridor is often referred to as the CMP corridor. The project received a presidential permit on January 15, 2021 and construction has started. [2] [View a map of the corridor.](https://ballotpedia.org/Maine_Question_1,_Electric_Transmission_Line_Restrictions_and_Legislative_Approval_Initiative_(2021)#Background)

This question is a **citizen initiative**, which is a way for Mainers to propose new laws. In order to become a valid initiative, a petition supporting the initiative must collect over 60,000 signatures. 

# Follow the money
A current lease related to this initiative would bring $65,000 annually for 25 years to the Public Reserved Lands Management Fund managed by the Department of Agriculture. [3]

# Pros
The primary arguments for this referendum are:
* Some people believe the corridor will benefit Massachusetts more than Maine.
* The NECEC is within a forested area that some want to protect.

# Cons
The primary arguments against this referendum are:
* It would set a precedent for changing laws retroactively. This could mean that things done legally today could become illegal if a law was changed in the future with a retroactive date.
* The NECEC transmission line is already under construction and terminating the lease will cost the state money, electricity, and jobs. [3]
* It would transfer decisions about infrastructure projects to the legislature instead of other state agencies that currently have processes for vetting the projects. [3]

# Who cares

Support [2]
* No CMP Corridor
* State Sen. Richard Bennett (R)
* State Sen. Russell Black (R)
* State Sen. Paul T. Davis (R)
* State Sen. Chloe Maxmin (D)
* State Rep. Seth Berry (D)
* State Rep. Nicole Grohoski (D)
* State Rep. Allison Hepler (D)
* State Rep. H. Scott Landry Jr. (D)
* State Rep. William Pluecker (Independent for Maine Party)
* State Rep. Jennifer Poirier (R)
* State Rep. Lynne Williams (D) Opposition
* Calpine Corp.
* NextEra Energy Resources, LLC
* Vistra Energy Corp.
* Food and Water Watch

Opposition
* Central Maine Power Company 
* Hydro-Québec Energy Services (U.S.) Inc. 
* Maine State Chamber of Commerce 
* Clean Energy Matters

# Further reading
[Full text](https://www.maine.gov/sos/cec/elec/citizens/line.pdf)
[Ballotpedia article](https://ballotpedia.org/Maine_Question_1,_Electric_Transmission_Line_Restrictions_and_Legislative_Approval_Initiative_(2021))
[NewsCenter Maine Video](https://www.newscentermaine.com/article/news/politics/ballot-question-1-explained-high-impact-transmission-cmp-central-maine-power-corridor-new-england-clean-energy-corridor/97-8d9808c3-380e-4d37-b0c7-d78870f22d1a)

# References
_Put the number in brackets above to indicate a footnote to a reference._
1. Maine State Legislature. [Sec. 1. 12 MRSA §1852, sub-§4](https://www.maine.gov/sos/cec/elec/citizens/line.pdf). Accessed September 25 2021.
2. Ballotpedia State Desk. [Maine Question 1, Electric Transmission Line Restrictions and Legislative Approval Initiative (2021)
](https://ballotpedia.org/Maine_Question_1,_Electric_Transmission_Line_Restrictions_and_Legislative_Approval_Initiative_(2021)). Ballotpedia. Accessed September 25, 2021.
3. NewsCenter Maine. [Ballot Question 1 explained](https://www.newscentermaine.com/article/news/politics/ballot-question-1-explained-high-impact-transmission-cmp-central-maine-power-corridor-new-england-clean-energy-corridor/97-8d9808c3-380e-4d37-b0c7-d78870f22d1a)
4. Bellows, Shenna. [Maine Citizen's Guide to the Referendum Election](https://www.maine.gov/sos/cec/elec/upcoming/pdf/11-21citizensguide.pdf). Accessed October 2, 2021.

# Image
https://commons.wikimedia.org/wiki/File:Transmission_line_towers_and_high_tension_lines_1a35251v.jpg

# Tags
Electricity
Retroactive
Citizen's Initiative

# Election date
11/02/2021

**Comment by shannonmcharg** [comment]
I started populating the content for this question above.  Feel free to edit and add stuff.

**Comment by shannonmcharg** [comment]
I added more to this one.  I haven't dug all the way into the background yet, if anyone wants to look into that.

**Comment by shannonmcharg** [comment]
This one's ready to review.  Does anyone have anything to add to the pro and con lists?

**Comment by shannonmcharg** [comment]
Updated pros and cons now that the Maine Citizen's Guide to the Referendum Election is available.

**Comment by relspeedwagon** [comment]
Added a space between the footnote and "View a map of the corridor" link, but did not find any real changes needed.  Expl seems very clear and thorough.
