### ISSUE TITLE
Question 2: Transportation Bond

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#222]
# Question title
Transportation

# Description (will display on homepage)
This measure would allow the state to borrow $100 million for transportation improvements.

# The gist
Passing this question would allow the state to borrow $100 million, matched by $253 million in federal and other funds, for transportation improvements.

# Ballot question (exact text of the question)
Do you favor a $100,000,000 bond issue to build or improve roads, bridges, railroads, airports, transit facilities and ports and make other transportation investments, to be used to leverage an estimated $253,000,000 in federal and other funds?

# Yes means
I am in favor of issuing the $100 million bond to address infrastructure improvements.

# No means
I do not want Maine to borrow $100 million to address infrastructure improvements.

# Tell me more
Passing this question would allow the State of Maine to borrow $100 million for a variety of infrastructure improvements, including roads, bridges, railroads, airports, transit and ports.[2 ]The bulk of the money will go towards high priority highways and bridges.

This is a bond issue – if voters approve the bond, it means that the State of Maine is allowed to borrow money for the project described in the ballot question and has to pay it back over 10 years. [Learn more about how bonds work.](https://www.maineballot.org/bonds/)

# Follow the money
Principal: $127,500,000
Interest:  $100,000,000
Total cost:  $27,500,000

The money will be used to
* $85 million for highways and bridges [2]
* $15 million for rail, aviation, ports, and active transportation. [2]

The money will be coming from
* $100 million bond issued by the state and paid back through the budget and taxes over 10 years. [2]
* $253 million in matching funds from the federal government and other sources. [2]

# Pros
The primary arguments for this referendum are:
* Maine’s roads and infrastructure are deteriorating.
* Makes up for some of the shortfall in gas taxes from fuel-efficient vehicles that have left the funds for highway repairs insufficient.
* Issuing the bond opens up matching funds.
* Interest rates are currently low, making it a good time to invest.

# Cons
The primary arguments against this referendum are:
* Maine already has $110.53 million in outstanding bond debt that this will add to and it could lead to increased taxes. [3]

# Who cares
Nobody has registered support or opposition to this bond.

# Further reading
[Full text](http://legislature.maine.gov/ros/LawsOfMaine/breeze/Law/getDocById/?docId=78979)
[Ballotpedia article](https://ballotpedia.org/Maine_Question_2,_Transportation_Infrastructure_Bond_Issue_(2021))

# References
_Put the number in brackets above to indicate a footnote to a reference._
1. Maine State Legislature. [An Act To Authorize a General Fund Bond Issue To Improve Transportation](http://legislature.maine.gov/ros/LawsOfMaine/breeze/Law/getDocById/?docId=78979). Accessed September 19, 2021.
2. Ballotpedia State Desk. [Maine Question 2, Transportation Infrastructure Bond Issue (2021)](https://ballotpedia.org/Maine_Question_2,_Transportation_Infrastructure_Bond_Issue_(2021)). Ballotpedia. Accessed September 19, 2021.
3. Bellows, Shenna. [Maine Citizen's Guide to the Referendum Election](https://www.maine.gov/sos/cec/elec/upcoming/pdf/11-21citizensguide.pdf). Accessed October 2, 2021.

# Image
Same image as this question: https://www.maineballot.org/july%202020%20election/q2_transportation/

# Tags
Bond, Transportation

# Election date
11/02/2021

**Comment by shannonmcharg** [comment]
I started content for this question above.  Feel freed to edit or add anything.  We can probably copy a lot from previous transportation bond questions in the archive.

Here's the most recent one: https://www.maineballot.org/july%202020%20election/q2_transportation/

**Comment by relspeedwagon** [comment]
Hey @shannonmcharg !  Added a few comments/Q's to the text above.  Full comment is between <--  [ Original Text ]  --> 
Let me know if comments are correct or need changes and I'll come clean everything up :)

**Comment by shannonmcharg** [comment]
@relspeedwagon Thanks for reviewing.  Good catches!  I addressed your comments.

**Comment by shannonmcharg** [comment]
Updated numbers now that the Maine Citizen's Guide to the Referendum Election is available.

**Comment by relspeedwagon** [comment]
@shannonmcharg Sorry, just getting back to this!  Looks good except am I correct to think the "total cost" figures might be mixed up?  
Written as:
Principal: $127,500,000
Interest: $100,000,000
Total cost: $27,500,000

Should this be:
Principal: $100,000,000
Interest: $27,500,000
Total cost: $127,500,000 ?

**Comment by shannonmcharg** [comment]
Yeah, you're right.

**Comment by shannonmcharg** [comment]
I fixed it in the PR
