### ISSUE TITLE
Question 3: Right to Food

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#223]
# Question title
Right to Food

# Description (will display on homepage)
This resolution would give citizens the explicit right to grow their own food.

# The gist
This resolution would give citizens the explicit right to grow, raise, harvest, produce and consume their own food.

# Ballot question (exact text of the question)
"Do you favor amending the Constitution of Maine to declare that all individuals have a natural, inherent and unalienable right to grow, raise, harvest, produce and consume the food of their own choosing for their own nourishment, sustenance, bodily health and well-being?"[1]

# Yes means
I am in favor of amending the state constitution so that all individuals have the right to grow, raise, harvest, produce and consume the food of their choosing.

# No means
I don't want to amend the state constitution.

# Tell me more
This measure would allow individuals to grow, raise, harvest, produce and consume food as long as they are not trespassing on somebody else's property or stealing.  It would also ensure individuals have the right to save and exchange seeds.

This question is a **constitutional resolution**, which, if passed, would make a change to the state constitution.

# Follow the money
There's no money directly involved with this referendum.

# Pros
The primary arguments for this referendum are:
* It would give individuals an explicit right to feed themselves.
* It wouldn't allow individuals to trespass on or steal other people's property.
* It would allow individuals to save and exchange seeds.

# Cons
The primary arguments against this referendum are:
* It could infringe on seed patents. [3]
* Some believe the language is too vague.[3]
* It could allow people to sidestep existing regulations related to things like animal welfare, pollution, local ordinances, or public safety. [3]

# Who cares

Support [2]

- State Sen. Craig Hickman (D) 
- State Sen. David Miramant (D) 
- State Rep. Jonathan Connor (R) 
- State Rep. Michelle Dunphy (D) 
- State Rep. William Faulkingham (R) 
- State Rep. Justin Fecteau (R) 
- State Rep. H. Scott Landry Jr. (D) 
- State Rep. Laurel Libby (R) 
- State Rep. William Pluecker (Independent for Maine Party) 
- State Rep. Jennifer Poirier (R) 
- State Rep. Heidi Sampson (R) 

Opposition [2]

- Animal Rights Maine 
- Maine Animal Coalition 
- Maine Farm Bureau 
- Maine Friends of Animals 
- Maine Municipal Association 
- Maine Potato Board 
- Maine Veterinary Medical Association 

# Further reading
[Full text](http://legislature.maine.gov/ros/LawsOfMaine/breeze/Law/getDocById/?docId=78982)
[Ballotpedia article](https://ballotpedia.org/Maine_Question_3,_Right_to_Produce,_Harvest,_and_Consume_Food_Amendment_(2021))

# References
_Put the number in brackets above to indicate a footnote to a reference._
1. Maine State Legislature. [RESOLUTION, Proposing an Amendment to the Constitution of Maine To Establish a Right to Food](http://legislature.maine.gov/ros/LawsOfMaine/breeze/Law/getDocById/?docId=78982). Accessed October 2, 2021.
2. Ballotpedia State Desk. [Maine Question 3, Right to Produce, Harvest, and Consume Food Amendment (2021)
](https://ballotpedia.org/Maine_Question_3,_Right_to_Produce,_Harvest,_and_Consume_Food_Amendment_(2021)).  Ballotpedia. Accessed October 2, 2021.
3. Bellows, Shenna. [Maine Citizen's Guide to the Referendum Election](https://www.maine.gov/sos/cec/elec/upcoming/pdf/11-21citizensguide.pdf). Accessed October 2, 2021.

# Image
https://commons.wikimedia.org/wiki/File:Butternut_Squash_with_dried_seeds.JPG
# Tags
Constitutional Resolution, Food

# Election date
11/02/2021

**Comment by shannonmcharg** [comment]
Started this one.  Feel free to edit or add anything.

**Comment by shannonmcharg** [comment]
This one is ready to review.

**Comment by relspeedwagon** [comment]
Thank you @shannonmcharg !  Very sorry, did not mean to sleep on this :(  All looks good to me, just changed one minor typo.

**Comment by shannonmcharg** [comment]
@relspeedwagon Where was the typo, so I can update the PR?

**Comment by relspeedwagon** [comment]
Whoops! Yes, sorry was just doubling back to say.  Not really a big "typo" but "sidestep" is one word (last line under "Cons")

**Comment by shannonmcharg** [comment]
Fixed in the PR.
