### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by giosce** [OpenMaine/maineballot#241]
Hi,
this is a great project!
I'm working on making https://projects.brigade.network/ more relevant.
For this reason I'm reaching out to Code for America Brigades projects to ask/recommend to have some tags (topics) in your repos.
This project falls under Priority Action Areas, "Voting Rights", I'm not dictating how to tags the projects, one idea could be paa-voting-rights or just voting-rights or something you find relevant (right now you don't have any topic).
If you'd like to discuss further you can write me at giosce@verizon.net, I hope to list your project soon!

**Comment by giosce** [comment]
Hi, we use the github topics, from the "About" section at the top right of the repo website.

![image](https://user-images.githubusercontent.com/16311029/137973052-fed9eedc-ac7c-4c42-ad0b-5827b533c13b.png)

**Comment by shannonmcharg** [comment]
Tags added.
