### ISSUE TITLE
Update local election content: Androscoggin county

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#255]
Spreadsheet: https://docs.google.com/spreadsheets/d/1dk58MD0qBAM37BDOZwKIz10hp5AARAIX8u_qvuDnYaI/edit#gid=0
Instructions: https://github.com/OpenMaine/maineballot/wiki/Updating-Maine-Ballot-for-an-upcoming-election

**Comment by inomyabcs** [comment]
All towns updated on Spreadsheet for June 2022
