### ISSUE TITLE
Question 1: Voter Approval for Borrowing

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#320]
# Question title
Voter Approval for Borrowing
 
# Description (will display on homepage)
This measure would require voter approval for large spending by certain government-controlled entities and utilities.

# The gist
This citizen's initiative would require voter approval for spending over $1 billion by certain government-controlled entities and utilities. The initiative was started in response to the bills to create a consumer-owned utility (see Question 3).

# Ballot question (exact text of the question)
Do you want to bar some quasi-governmental entities and all consumer-owned electric utilities from taking on more than $1 billion in debt unless they get statewide voter approval?

# Yes means
I want to require voter approval for spending by the specified government-controlled entities and utilities over $1 billion.

# No means
I don't want to require voter approval for spending by the specified government-controlled entities and utilities over $1 billion.

# Tell me more
The government-controlled entities and utilities covered by this initiative include quasi-independent state entities, reporting entities, municipal electric districts, consumer-owned transmission and distribution utilities, and cooperative or rural
electrification cooperatives. [1]

"Exemptions are provided for debt issued by the Maine Public Employees Retirement System, the Finance Authority of Maine, the Maine Health and Higher Education Facilities Authority, the Department of Transportation, the Maine Turnpike Authority, municipalities and counties and the Maine Municipal Bond Bank and for certain education-related programs." [1]

The number of times approval is needed for borrowing is expected to be small. [1]

This question is a **citizen's initiative**, which is a way for Mainers to propose new laws. In order to become a valid initiative, a petition supporting the initiative must collect over 60,000 signatures.

# Follow the money
If there are enough requests for borrowing that it requires a second ballot for a given election, it would cost $266,000 to add a second ballot.

# Pros
The primary arguments for this referendum are:
* It would give voters a voice in large spending. [3]
* It would help keep the specified entities and utilities in check.

# Cons
The primary arguments against this referendum are:
* It could be seen as a way to discourage the creation of a consumer-owned utility (see Question 3).

# Who cares[2]

Support
* No Blank Checks
* Avangrid, Inc.
* Maine State Chamber of Commerce
* Sportsman’s Alliance of Maine

Opposition
There is no registered opposition.

# Further reading
[Full Text](https://www.maine.gov/sos/cec/elec/citizens/VoterApprovalBorrowingFINAL11.10.pdf)<br>
[Ballotpedia Atricle](https://ballotpedia.org/Maine_Question_1,_Voter_Approval_of_Borrowing_Above_$1_Billion_by_State_Entities_and_Electric_Cooperatives_Initiative_(2023))<br>
[Portland Press Herald Article](https://www.pressherald.com/2023/10/02/question-1-voters-could-have-a-say-in-certain-big-spending/)

# References
_Put the number in brackets above to indicate a footnote to a reference._
1. Bellows, Shenna. [Maine Citizen’s Guide to the Referendum Election](https://www.maine.gov/sos/cec/elec/upcoming/pdf/citizensguide23.pdf). Accessed October 6, 2023.
2. Ballotpedia State Desk. [Maine Question 1, Voter Approval of Borrowing Above $1 Billion by State Entities and Electric Cooperatives Initiative (2023)](https://ballotpedia.org/Maine_Question_1,_Voter_Approval_of_Borrowing_Above_$1_Billion_by_State_Entities_and_Electric_Cooperatives_Initiative_(2023)). Ballotpedia. Accessed October 6, 2023.
3. Singer, Stephen. [Question 1: Voters would have a say in certain big spending](https://www.pressherald.com/2023/10/02/question-1-voters-could-have-a-say-in-certain-big-spending/). Portland Press Herald. Accessed October 6, 2023.
4. Maine Secretary of State [An Act To Require Voter Approval of Certain Borrowing by Government-controlled Entities and Utilities and To Provide Voters More Information Regarding that Borrowing](https://www.maine.gov/sos/cec/elec/citizens/VoterApprovalBorrowingFINAL11.10.pdf). Accessed October 6, 2023.

# Image
Use same image from this question: https://www.maineballot.org/november%202016%20election/q4_minimumwage/

# Tags
Consumer Utility, Citizen's Initiative, Borrowing

# Election date
Nov 7, 2023

**Comment by shannonmcharg** [comment]
Ballotpedia: https://ballotpedia.org/Maine_Question_1,_Voter_Approval_of_Borrowing_Above_$1_Billion_by_State_Entities_and_Electric_Cooperatives_Initiative_(2023)

**Comment by shannonmcharg** [comment]
https://www.pressherald.com/2023/10/02/question-1-voters-could-have-a-say-in-certain-big-spending/

**Comment by shannonmcharg** [comment]
@inomyabcs Will you please review this one, since it's related to Question 3?

**Comment by shannonmcharg** [comment]
@inomyabcs Ready to review in the build. https://deploy-preview-328--awesome-lamarr-6d076d.netlify.app/november%202023%20election/q1_quasiborrowing/

**Comment by inomyabcs** [comment]
Nice and simple. I don't see anything glaring. No spelling errors, grammar is okey-dokey, and no formatting errors in Firefox.
