### ISSUE TITLE
Question 3: Consumer-owned Utility

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#322]
# Question title
Consumer-owned Utility

# Description (will display on homepage)
This measure would create a consumer-owned utility.

# The gist
This citizen initiative would require the investor-owned utilities, mainly Central Maine Power and Versant Power, to sell their distribution and transmission facilities to a new consumer-owned company. The consumer-owned company would be known as the Pine Tree Power Company and would be managed by an executive board composed of 7 elected representatives and 6 expert members.

An additional related ballot question, Question 1, could add a layer of complexity to a successful Yes vote by requiring future ballot questions for any issuance of debt that is more than $1 billion. You may want to consider your choice for both questions together.

# Ballot question (exact text of the question)
Do you want to create a new power company governed by an elected board to acquire and operate existing for-profit electricity transmission and distribution facilities in Maine?[^1]

# Yes means
I am in favor of the creation of a consumer owned electric utility that would replace Central Maine Power and Versant Power.

# No means
I don't want Central Maine Power and Versant Power to be replaced with a consumer owned electric utility.

# Tell me more
From the official ballot summary[^3]:

> "This initiated bill creates the Pine Tree Power Company, a privately operated, nonprofit, consumer-owned utility controlled by a board the majority of the members of which are elected. The company's purposes are to provide for its customer-owners in this State reliable, affordable electric transmission and distribution services and to help the State meet its climate, energy and connectivity goals in the most rapid and affordable manner possible.

> The Pine Tree Power Company is not permitted to use general obligation bonds or tax dollars of the State. The company finances itself by issuing debt against its future revenues to purchase the facilities of investor-owned electric transmission and distribution utilities in the State. The fair market value of the acquisition is either negotiated or determined by a refereed process. The Pine Tree Power Company Board contracts a nongovernmental team to operate the facilities, and the operations team is required to retain all workers of the purchased utilities.

> The company is subject to property taxation and must pay property tax in the same manner as an investor-owned transmission and distribution utility. The company is subject to rate-making and other oversight by the Public Utilities Commission and is required to administer programs for net energy billing, non-wires alternatives, supply procurement and low-income assistance programs.

> The company is governed by a board of 13 members, 7 of whom are each elected to represent 5 State Senate districts, as well as 6 designated expert members. The board is subject to freedom of access laws and to laws preventing conflicts of interest.

> The initiated bill also directs the Public Utilities Commission beginning January 1, 2025 to find a transmission and distribution utility unfit to serve and to direct the sale of the utility if the utility meets certain criteria."

This bill is citizen-initiated with the purpose to replace Maine's two investor-owned electricity transmission and distribution utilities, Central Maine Power and Versant Power. The new company, Pine Tree Power Company, is specified with 8 purposes:
1. Delivering electricity in a safe, affordable, and reliable manner
2. Ensuring excellence, timeliness, and accuracy in billing, metering, and customer service
3. Providing an open, supportive, and competitive platform to develop and deploy renewable generation, storage, efficiency and beneficial electrification technologies
4. Assisting the State in rapidly meeting or exceeding climate goals
5. Improving Internet connectivity
6. Advancing economic, environmental, and social justice
7. Providing for accountable governance
8. Providing economic growth and benefits for the State

Other than the purchase of all of the utility infrastructure at prices to be negotiated between Pine Tree Power and the two investor utilities, Pine Tree Power will be obligated to contract with one or more private-sector operators. The operators would be responsible for the day-to-day operation of the transmission grid, maintenance, billing, and customer service. This contract is performance-based and not capitally funded. Additionally, Pine Tree Power would be required to offer to hire all qualified, nonexempt employees of Central Maine Power and Versant Power. The only employees exempted from hire would be members of each utility's executive board.

The Public Utilities Commission would remain responsible for oversight of Pine Tree Power and must approve of the initial 5-year plan to meet affordability, reliability, decarbonization, and connectivity goals.

This question is a **citizen's initiative**, which is a way for Mainers to propose new laws. In order to become a valid initiative, a petition supporting the initiative must collect over 60,000 signatures.

# Follow the money
The official fiscal impact statement does not speak to estimated costs of purchasing the assets of Central Maine Power or Versant Power[^3]. However, from the official filings as publicly traded companies, the relevant power utility plants of Central Maine Power are $4.2 billion[^5] and Versant Power are potentially $1.2 billion[^6][^7]. The Portland Press Herald reports that supporters cite a cost of $5 to $6 billion and opponents $13 billion[^4]. Any purchasing costs will be authorized through the issuance of bonds and operations costs are funded through the utility rates.

The official fiscal impact statement discusses costs related to the Public Utilities Commission oversight at $1.25 million for the first year and $2.25 million in subsequent years (this may be passed on to consumers through rate increases).

Any litigation arising from the purchasing of assets may also be passed on to consumers.

Costs related to the Maine Clean Election program for any candidates applying to the 13-person governing board are estimated to be $335,450 and $273,750 for the first two fiscal years after implementation. Revenue from candidate contributions are estimated at $13,900 and $9,900 for the first two fiscal years. The lower pace of elections regarding board members will drop clean election costs to $110,764 or $166,145 depending on 2 or 3 member election cycles.

# Pros
The primary arguments for this referendum are:
* Local control of the utility when compared to CMP, a subsidiary of Avangrid through Iberdrola in Spain, and Versant, part of ENMAX in Canada
* A responsive company that has more consumer input through elected representatives
* Potential for reduced electricity rates or more system reliability through a reduced need to incentivize profits
* Lower interest rate costs for borrowing money to upgrade and expand the grid

# Cons
The primary arguments against this referendum are:
* Savings through lower interest rates may not help greatly with the projected steep initial upfront purchasing of assets
* The proposed Pine Tree Power Executive Board may still delay system improvements if it would help keep rate costs down and consequently may worsen system reliability

# Who cares
## Public comment
During the public comment period, no comments were submitted in support or opposition of question 3.

## General Support
* [Sierra Club](https://www.sierraclub.org/maine/blog/2023/09/sierra-club-maine-2023-ballot-initiative-voter-guide)
* [Maine State Nurses Association](https://mainebeacon.com/maine-nurses-union-backs-plan-to-oust-cmp-versant/)
* [Maine People's Alliance](https://mainebeacon.com/sierra-club-endorses-measure-to-replace-cmp-versant-with-consumer-owned-utility/)
* [350.org](https://350.org/pine-tree-endorsement/)
* [Natural Resources Council of Maine](https://www.nrcm.org/blog/case-for-public-power/?eType=EmailBlastContent&eId=5d941bfc-344f-4ad1-8386-e89c12ea19cb)
* [United States Senator Bernie Sanders (I-VT)](https://www.mainepublic.org/politics/2023-07-27/bernie-sanders-endorses-plan-to-create-nonprofit-electric-utility-in-maine)

## General Opposition
* [International Brotherhood of Electrical Workers (IBEW)](https://www.mainepublic.org/politics/2023-10-05/heres-everything-we-know-about-the-referendum-to-replace-cmp-and-versant-with-pine-tree-power)
* [Maine AFL-CIO](https://wgan.com/news/074470-two-labor-groups-advocate-against-pine-tree-power/)
* [Portland Community Chamber of Commerce](https://www.pressherald.com/2023/09/14/portland-chamber-slams-public-power-proposal-as-activists-demonstrate/)
* [Maine Governor Janet Mills (D-ME)](https://www.bangordailynews.com/2023/09/20/politics/janet-mills-utility-takeover/)

## Campaign Financing
Ballotpedia reports that there are three Political Action Committees (PACs) registered for this ballot measure[^2]. Two are in opposition and one is in support.

### Support PACs
* [Our Power](https://ourpowermaine.org/): As of 30 September, 2023, Ballotpedia reported contributions of $1.07 million with expenditures of $1.01 million.

### Opposition PACs
* [Maine Affordable Energy](https://maineaffordableenergy.org/)
* [Maine Energy Progress](https://www.maineenergyprogress.com/)
* Combined contributions of $35.5 million and expenditures of $29.6 million

# Further reading
[Full text](https://www.maine.gov/sos/cec/elec/citizens/Pine%20Tree%20Power%20Petition.pdf)<br>
[Ballotpedia article](https://ballotpedia.org/Maine_Question_3,_Pine_Tree_Power_Company_Initiative_(2023))<br>
[Portland Press Herald Article](https://www.pressherald.com/2023/10/02/question-3-voters-could-reshape-maines-energy-landscape/)<br>
[Office of the Public Advocate Report](https://www.maine.gov/meopa/sites/maine.gov.meopa/files/inline-files/Pine%20Tree%20Power%20Fact%20Sheet.pdf)

# References
1. Maine Secretary of State. [An Act To Create the Pine Tree Power Company, a Nonprofit, Customer-owned Utility](https://www.maine.gov/sos/cec/elec/citizens/Pine%20Tree%20Power%20Petition.pdf). Accessed October 7, 2023.
2. Ballotpedia State Desk. [Maine Question 3, Pine Tree Power Company Initiative (2023)](https://ballotpedia.org/Maine_Question_3,_Pine_Tree_Power_Company_Initiative_(2023)). Ballotpedia. Accessed October 7, 2023.
3. Bellows, Shenna. [Maine Citizen’s Guide to the Referendum Election](https://www.maine.gov/sos/cec/elec/upcoming/pdf/citizensguide23.pdf). Accessed October 7, 2023.
4. Singer, Stephen. [Question 3: What you need to know about the Pine Tree Power referendum](https://www.pressherald.com/2023/10/02/question-3-voters-could-reshape-maines-energy-landscape/). Portland Press Herald. Accessed October 7, 2023.
5. Avangrid. [Central Maine Power Company and Subsidiaries, 2nd Quarter 2023 Consolidated Financial Statements] (https://s24.q4cdn.com/489945429/files/doc_financial/Supplemental_Report/2023/08/cmp-fs-q2-2023-final-8-9-2023.pdf). Accessed October 7, 2023.
6. Versant Power's electricity and transmission assets are consolidated into Enmax's (the parent company) investor report[^7]. Versant Power's segment was estimated by calculating the percent difference of the distribution volume of Enmax Power and Versant Power. This was then applied to the Property, Plant, and Equipment financial report total.
7. Enmax. [2022 ENMAX Financial Report] (https://www.enmax.com/AboutUsSite/Reports/2022-ENMAX-Financial-Report.pdf). Accessed October 7, 2023.

# Image
Use image from this question: https://www.maineballot.org/november%202021%20election/q1_electrictransmissionline/

# Tags
Citizen's Initiative, Electricity

# Election date
Nov 7, 2023

**Comment by shannonmcharg** [comment]
Ballotpedia: https://ballotpedia.org/Maine_Question_3,_Pine_Tree_Power_Company_Initiative_(2023)

**Comment by shannonmcharg** [comment]
https://www.pressherald.com/2023/09/05/utility-question-likely-to-be-tied-up-in-court-for-years/?fbclid=IwAR2b2odY9RzFuHkmA3XXPBdyAgba_8h8cUtJ3uoo0cs3CzdODqpL88eBCYM

**Comment by inomyabcs** [comment]
Still in draft. Will be determining sources for talking about the hot topic of money next.

**Comment by shannonmcharg** [comment]
https://www.pressherald.com/2023/10/02/question-3-voters-could-reshape-maines-energy-landscape/

**Comment by shannonmcharg** [comment]
https://www.pressherald.com/2023/09/19/prices-at-smaller-utilities-work-their-way-into-debate-over-maines-energy-future/

**Comment by inomyabcs** [comment]
Pros/Cons and Who Cares are left remaining. I'll hit those up later tonight.

**Comment by inomyabcs** [comment]
@shannonmcharg Can you take a look at this? I'm about to pop over to Question 1 and read through it.

**Comment by shannonmcharg** [comment]
@inomyabcs Looks good. I made a few edits and will start moving it into the build.

**Comment by shannonmcharg** [comment]
@inomyabcs Ready to review in the build. https://deploy-preview-328--awesome-lamarr-6d076d.netlify.app/november%202023%20election/q3_pinetreepower/
