### ISSUE TITLE
Question 6: Constitutional Provision Printing

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#325]
# Question title
Constitutional Provision Printing

# Description
This measure would add sections of the constitution related to Indian treaty obligation back into printed copies of the constitution.

# The gist
This constitutional amendment would amend the Constitution of Maine to require that official printed copies include the whole document, including section related to Indian treaty obligations that were removed in 1876.

# Ballot question (exact text of the question)
Do you favor amending the Constitution of Maine to require that all of the provisions of the Constitution be included in the official printed copies of the Constitution prepared by the Secretary of State?

# Yes means
I am in favor of amending the printed Maine Constitution to include the removed sections.

# No means
I want to keep the constitution as is.

# Tell me more
In 1876 after a statewide vote, Article X of Maine’s constitution was amended with Section 7,  which prohibited Section 1, Section 2, and Section 5 of Article X from appearing in printed versions of the Constitution but kept the text of those sections as valid law. The sections removed from printed copies of the Constitution by Section 7 included language pertaining to the Indian Treaty Obligations of Maine.[2]

The proposed resolution would revert the change made in Article X, Section 7 and again include sections 1, 2, and 5 of Article X in official printed copies of the Maine Constitution.

This question is a **constitutional amendment**, which, if passed, would make a change to the state constitution.

# Follow the money
There's no money directly involved with this referendum.

# Pros
The primary arguments for this referendum are:
* Including the full text of Article X in printed copies of the Maine Constitution honors a shared history between tribal nations and the State of Maine.[2]
* Printing the Maine Constitution in its entirety makes it more easily accessible to the public and is essential to supporting a fair and free democracy.[2]

# Cons
The primary arguments against this referendum are:
* The idea that Article X, Sections 1, 2, and 5 were removed from printed copies of the Constitution as part of an effort to evade treaty obligations is not supported by evidence. Making this change to the Constitution would perpetuate an unsupported theory.[2] 
* Amending the Maine Constitution to include Article X, Sections 1, 2, and 5 in printed copies will not affect any laws, but could be confusing for citizens who wrongly believe that the original treaties referenced in the articles still have legal effect.[2]

#Who cares [2]

Support
* State Sen. Richard Bennett (R) 
* State Rep. Rachel Ross (D) 
* State Rep. Samuel Zager (D) 
* Maine Secretary of State Shenna Bellows (D) 
* Maine Attorney General Aaron Frey (D) 
* Wabanaki Alliance 
* League of Women Voters of Maine 
* Sierra Club Maine 

Opposition
* Maine Gov. Janet T. Mills (D) 

# Further reading
[Full text](https://legislature.maine.gov/bills/getPDF.asp?paper=HP0048&item=1&snum=131)
[Ballotpedia article](https://ballotpedia.org/Maine_Question_6,_Require_Indian_Treaty_Obligations_and_Other_Constitutional_Provisions_Included_in_Official_Printing_Amendment_(2023))

# References
1. Maine State Legislature. [RESOLUTION, Proposing an Amendment to Article X of the Constitution of Maine Regarding the Publication of Maine Indian Treaty Obligations](https://legislature.maine.gov/bills/getPDF.asp?paper=HP0048&item=1&snum=131). Accessed October 1, 2023.
2. Ballotpedia State Desk. [Maine Question 6, Require Indian Treaty Obligations and Other Constitutional Provisions Included in Official Printing Amendment (2023)](https://ballotpedia.org/Maine_Question_6,_Require_Indian_Treaty_Obligations_and_Other_Constitutional_Provisions_Included_in_Official_Printing_Amendment_(2023)). Ballotpedia. Accessed October 1, 2023.
3. [Bellows, Shenna. Maine Citizen's Guide to the Referendum Election](https://www.maine.gov/sos/cec/elec/upcoming/pdf/citizensguide23.pdf) Accessed October 1, 2023.
4. Ohm, Rachel. [Questions 5 through 8: What you need to know about the proposed constitutional amendments](https://www.pressherald.com/2023/10/06/questions-5-through-8-what-you-need-to-know-about-the-proposed-constitutional-amendments/). Portland Press Herald. Accessed October 6, 2023.

# Image
[Constitution](https://commons.wikimedia.org/wiki/File:Constitution_of_the_United_States,_page_1.jpg)

# Tags
Constitutional Amendment, Native American

# Election date
November 7, 2023

**Comment by shannonmcharg** [comment]
Ballotpedia: https://ballotpedia.org/Maine_Question_6,_Require_Indian_Treaty_Obligations_and_Other_Constitutional_Provisions_Included_in_Official_Printing_Amendment_(2023)

**Comment by relspeedwagon** [comment]
Added the body of this one, open for adding further detail

**Comment by shannonmcharg** [comment]
@relspeedwagon I think this one is good to go.

**Comment by shannonmcharg** [comment]
https://www.pressherald.com/2023/10/06/questions-5-through-8-what-you-need-to-know-about-the-proposed-constitutional-amendments/

**Comment by shannonmcharg** [comment]
@relspeedwagon This one's ready to review in the build. https://deploy-preview-328--awesome-lamarr-6d076d.netlify.app/november%202023%20election/q6_printingconstitution/
