### ISSUE TITLE
Question 7: Petition Circulation

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#326]
# Question title
Petition Circulation

# Description
This measure would remove the requirement for people circulating petitions to be Maine residents who are registered to vote.

# The gist
This constitutional amendment would remove the requirement for people circulating petitions to be Maine residents who are registered to vote. 

# Ballot question (exact text of the question)
Do you favor amending the Constitution of Maine to remove a provision requiring a circulator of a citizen's initiative or people's veto petition to be a resident of Maine and a registered voter in Maine, requirements that have been ruled unconstitutional in federal court?

# Yes means
I am in favor of removing the residency and registration requirements for petition circulators from the Maine Constitution.

# No means
I don't want this change to the Maine Constitution. 

# Tell me more
Currently the Maine Constitution requires anyone collecting signatures for People’s Vetoe and Direct Initiative petitions to be a resident and registered voter in Maine.  This resolution would remove the requirement and align Maine’s constitution with federal law.

Federal courts have already ruled that the residency requirement for petitioners is unconstitutional and can’t be enforced by the state of Maine.[3]

This question is a **constitutional amendment**, which, if passed, would make a change to the state constitution.

# Follow the money

There's no money directly involved with this referendum. 

# Pros
The primary arguments for this referendum are:
* Aligns Maine’s constitution with federal court decisions regarding the First Amendment
* Aligns Maine with the majority of other states with statewide initiative or veto referendum processes

# Cons
The primary arguments against this referendum are:
*  It changes the Maine Constitution.

# Who cares

Support[2]
*State Sen. Craig Hickman (D) 
*State Rep. David Boyer (R) 
*State Rep. Laura Supica (D) 

Opposition
*No campaigns found in opposition[2]
*An argument against made by Garland, ME party co-chair, Linda Haskell (R)[2]

# Further reading
[Full text](https://legislature.maine.gov/bills/getPDF.asp?paper=SP0597&item=1&snum=131)
[Ballotpedia article](https://ballotpedia.org/Maine_Question_7,_Remove_Residency_Requirement_for_Initiative_Petition_Circulators_Amendment_(2023))

# References
_Put the number in brackets above to indicate a footnote to a reference._
1. Maine State Legislature. [RESOLUTION, Proposing an Amendment to the Constitution of
Maine to Align the Proceedings for Circulating Written Petitions for
People's Vetoes and Direct Initiatives with Federal Law](https://legislature.maine.gov/bills/getPDF.asp?paper=SP0597&item=1&snum=131).  Accessed October 1, 2023.
2. Ballotpedia State Desk. [Maine Question 7, Remove Residency Requirement for Initiative Petition Circulators Amendment (2023)](https://ballotpedia.org/Maine_Question_7,_Remove_Residency_Requirement_for_Initiative_Petition_Circulators_Amendment_(2023)). Accessed September 23, 2023.
3. Bellows, Shenna. [Maine Citizen's Guide to the Referendum Election](https://www.maine.gov/sos/cec/elec/upcoming/pdf/citizensguide23.pdf). Accessed October 1, 2023.
4. Ohm, Rachel. [Questions 5 through 8: What you need to know about the proposed constitutional amendments](https://www.pressherald.com/2023/10/06/questions-5-through-8-what-you-need-to-know-about-the-proposed-constitutional-amendments/). Portland Press Herald. Accessed October 6, 2023.

# Image
[Clipboard](https://upload.wikimedia.org/wikipedia/commons/c/c8/Clipboard.jpg)

# Tags
Constitutional Amendment, Petitions

# Election date
November 7th, 2023

**Comment by shannonmcharg** [comment]
Ballotpedia: https://ballotpedia.org/Maine_Question_7,_Remove_Residency_Requirement_for_Initiative_Petition_Circulators_Amendment_(2023)

**Comment by relspeedwagon** [comment]
Filled out the basics for this one, could have more detail added

**Comment by shannonmcharg** [comment]
@relspeedwagon Looks good. I made a few edits. I think this is ready to go in the PR, if you want to try doing that.

**Comment by shannonmcharg** [comment]
https://www.pressherald.com/2023/10/06/questions-5-through-8-what-you-need-to-know-about-the-proposed-constitutional-amendments/

**Comment by shannonmcharg** [comment]
@relspeedwagon This one's ready to review in the build. https://deploy-preview-328--awesome-lamarr-6d076d.netlify.app/november%202023%20election/q7_petitionvotingstatus/
