### ISSUE TITLE
Question 8: Voting Under Guardianship

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#327]
# Question title
Voting Under Guardianship

# Description (will display on homepage)
This measure would allow people under guardianship for mental illness to vote in elections for governor, senators, and representatives.

# The gist
This amendment would remove text from Article II Section 1 of the Maine Constitution that violates the Due Process Clause and the Equal Protection Clause found in the United States Constitution[1]. The sentence of relevance in the Maine Constitution is bolded, "Every citizen of the United States of the age of 18 years and upwards, **excepting persons under guardianship for reasons of mental illness**, having his or her residence established in this State, shall be an elector for Governor, Senators and Representatives, in the city, town or plantation where his or her residence has been established, if he or she continues to reside in this State; and the elections shall be by written ballot." 

# Ballot question (exact text of the question)
Do you favor amending the Constitution of Maine to remove a provision prohibiting a person under guardianship for reasons of mental illness from voting for Governor, Senators and Representatives, which the United States District Court for the District of Maine found violates the United States Constitution and federal law?

# Yes means
I am in favor of allowing those under guardianship for mental illness to vote for governor, senators, and representatives.

# No means
I don't want to allow those under guardianship for mental illness to vote for governor, senators, and representatives

# Tell me more
Guardianship is a legal relationship where one person is appointed by a court to manage the personal affairs of another person[2]. A Guardianship can be created over the objection of the person in question. 

There are two types of guardianship in Maine: limited and full. In _Doe vs Rowe_, the three plaintiffs were under full guardianship. Probate court can make exceptions to allow for a person to vote in elections, but it must be specifically requested at the time the person is placed under guardianship. Further motions can be put forth to modify a guardianship at a later date. The theme of _Doe vs Rowe_ is that the loss of voting privilege was not always communicated at the time that guardianship was implemented.

The restriction of voting by persons under guardianship due to reasons of mental illness was added to the Maine Constitution in 1965. Prior to the approval of the 1965 amendment, the Maine Constitution restricted voting to "paupers and persons under guardianship". There have been many attempts to remove this language either through legislative action in Maine law or ballot referendums (1997 and 2000), but all have them have not been successful so far.

Maine Legislative Document (L.D.) 1653, was introduced by Senator Craig Hickman on April 13th, 2023. This bill was successful in passing the Maine Legislature with the required supermajority to be placed on the November 2023 ballot.

Testimony given during the public hearing period came from the Legal Services for the Elderly (LSE) and a concerned citizen. LSE argued in favor of LD 1653 making a distinction in the full categorical exclusion of those under guardianship and the need to ensure that those that have the right to vote also need to have the capacity to vote[3]. The concerned citizen's testimony was not in favor and emphasized that voters must be of sound mind to be able to understand the issues at hand[4].

This question is a **constitutional amendment**, which, if passed, would make a change to the state constitution

# Follow the money

There's no money directly involved with this referendum. 

# Pros
The primary arguments for this referendum are:
* The state no longer enforces the provision in the Maine Constitution after resolution of the lawsuit _Doe v. Rowe_; therefore, the language should be removed.
* The Maine Constitution violates the Due Process and Equal Protection Clauses of the United States Constitution.

# Cons
The primary arguments against this referendum are:
* Probate Court, as part of the determination of placing someone under guardianship, could possibly allow someone to vote who is not of sound mind.

# Who cares[6]

Support
* Disability Rights Maine
* Legal Services for the Elderly
* Bill (LD 1653) Sponsors and Co-sponsors
** Senator Craig Hickman (Sponsor)
** Senator Stacy Brenner
** Representative Karen Montell
** Senator Cameron Reny
** Representative Morgan Reilly
** Representative Laura Supica 

Opposition
Support
* Disability Rights Maine
* Legal Services for the Elderly
* Bill (LD 1653) Sponsors and Co-sponsors
** Senator Craig Hickman (Sponsor)
** Senator Stacy Brenner
** Representative Karen Montell
** Senator Cameron Reny
** Representative Morgan Reilly
** Representative Laura Supica 
# Further reading
[Full Text](https://legislature.maine.gov/bills/getPDF.asp?paper=SP0658&item=3&snum=131)
[Ballotpedia Atricle](https://ballotpedia.org/Maine_Question_8,_Allow_Individuals_Under_Guardianship_for_Reasons_of_Mental_Illness_to_Vote_in_Elections_Amendment_(2023))

# References
1. Doe v. Rowe, [156 F. Supp. 2d 35 (D. Me. 2001)](https://casetext.com/case/doe-v-rowe). Accessed 3 September 2023.
2. Mainelse.org. (2021). [Conservatorship & Guardianship | Maine Legal Services for the Elderly](https://mainelse.org/handbook/planning-future/conservatorship-guardianship#:~:text=Yes%2C%20in%20Maine%20there%20are,all%20areas%20of%20your%20life). Accessed 3 September 2023.
3. Maine State Legislature. (26 April 2023). [Testimony of John Brautigam, Esq., Legal Services for the Elderly](https://legislature.maine.gov/bills/getTestimonyDoc.asp?id=172973). Accessed 3 September 2023.
4. Maine State Legislature. (n.d.) [Testimony to oppose LD 1653](https://legislature.maine.gov/bills/getTestimonyDoc.asp?id=10018790). Accessed 3 September 2023.
5. Bellows, Shenna. [Maine Citizen’s Guide to the Referendum Election](https://www.maine.gov/sos/cec/elec/upcoming/pdf/citizensguide23.pdf). Accessed October 3, 2023.
6. Ballotpedia State Desk. [Maine Question 8, Allow Individuals Under Guardianship for Reasons of Mental Illness to Vote in Elections Amendment (2023)](https://ballotpedia.org/Maine_Question_8,_Allow_Individuals_Under_Guardianship_for_Reasons_of_Mental_Illness_to_Vote_in_Elections_Amendment_(2023)). Accessed October 2, 2023.
7. Ohm, Rachel. [Questions 5 through 8: What you need to know about the proposed constitutional amendments](https://www.pressherald.com/2023/10/06/questions-5-through-8-what-you-need-to-know-about-the-proposed-constitutional-amendments/). Portland Press Herald. Accessed October 6, 2023.

# Image
Reuse image from this question: https://www.maineballot.org/june%202018%20election/q1_rankedchoicevoting/
# Tags
Constitutional Amendment, Mental Illness, Guardianship

# Election date
11/7/2023

**Comment by shannonmcharg** [comment]
Ballotpedia: https://ballotpedia.org/Maine_Question_8,_Allow_Individuals_Under_Guardianship_for_Reasons_of_Mental_Illness_to_Vote_in_Elections_Amendment_(2023)

**Comment by inomyabcs** [comment]
Filled in a good majority of this one. I would like to add more once the ballot measure public comments are released sometime during September.

**Comment by shannonmcharg** [comment]
@inomyabcs Thank you!

**Comment by inomyabcs** [comment]
I think I have this one ready for full review.

**Comment by shannonmcharg** [comment]
@inomyabcs This looks good. I made a few edits. I think it's ready to go into the PR if you want to do that.

**Comment by shannonmcharg** [comment]
https://www.pressherald.com/2023/10/06/questions-5-through-8-what-you-need-to-know-about-the-proposed-constitutional-amendments/

**Comment by shannonmcharg** [comment]
@inomyabcs This one is ready to review in the build. https://deploy-preview-328--awesome-lamarr-6d076d.netlify.app/november%202023%20election/q8_guardianelectors/
