### ISSUE TITLE
Change Master branch name to Main

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#336]
Sometime after the November election, does anyone have experience with doing this?

**Comment by inomyabcs** [comment]
Don't have experience, but it is right on the main [Settings](https://github,com/OpenMaine/maineballot/settings) page. Area highlighted below.

![image](https://github.com/OpenMaine/maineballot/assets/32985654/b635f797-e95c-48b2-8459-1753d19572a4)

**Comment by shannonmcharg** [comment]
Let's try it after the election, in case there are any unforeseen snags.

**Comment by inomyabcs** [comment]
Are we ready for this?

**Comment by shannonmcharg** [comment]
@inomyabcs Yes

**Comment by inomyabcs** [comment]
@shannonmcharg Change made. Looks like it was pretty seamless. Website is responding well. I can recommend closure.

**Comment by shannonmcharg** [comment]
@inomyabcs Looks good! Thanks for getting this done!
