### ISSUE TITLE
Search Console Verification

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#339]
Got an email from Google saying they're moving their domains to SquareSpace and I may lose Search Console Verificaiton.  Anyone know what we need to do?

Email:
![image](https://github.com/OpenMaine/maineballot/assets/12865238/a9342f64-7dc1-451e-b2f9-ba197beaf2fe)

What I have for options when I click the button in the email:
![image](https://github.com/OpenMaine/maineballot/assets/12865238/8ce98184-e1be-4e99-b68e-9bd11e64ce5d)

**Comment by shannonmcharg** [comment]
@IHIutch @rentry @inomyabcs Any of you able to help with this?

**Comment by IHIutch** [comment]
There should also be a way to add it with a meta tag like: `<meta content="..." name="google-site-verification">`. Probably the same value as a the TXT record. I can make a PR

**Comment by shannonmcharg** [comment]
@IHIutch Thank you!

**Comment by inomyabcs** [comment]
Well, I didn't intend for the issue to close. Feel free to reopen if the Search Console doesn't verify in 48 hours.

**Comment by rentry** [comment]
Doesn't this need to merge into `main` to resolve? That is, `main` is the branch connected to the actual domain name.

I think it's better to be safe than sorry, but I'm not sure why this is a problem to begin with. The domain was originally registered in google domains, so it should inherit auth in a move to Squarespace (also, 🙄). But I'm not sure it can verify in a branch other than the production branch.

**Comment by IHIutch** [comment]
If it was already connected with a static file or a meta tag it probably wouldn't matter. I think the warning is just that some DNS configuration details  could be lost between the during the migration.

@shannonmcharg you should just be able to hit "verify" in GSC and see if Google sees the new meta tag

**Comment by shannonmcharg** [comment]
Verification failed.
![image](https://github.com/OpenMaine/maineballot/assets/12865238/cb784eb7-c282-4a24-a43f-f64a7a421331)

**Comment by IHIutch** [comment]
You may have to choose a different verification method. There should be an option called "HTML Tag" which looks like this: 
<img width="929" alt="Screenshot 2024-03-04 at 9 30 39 AM" src="https://github.com/OpenMaine/maineballot/assets/20825047/8ed6d59c-ca94-44a4-9cf3-31c0401b92c6">

**Comment by shannonmcharg** [comment]
HTML Tag:

google-site-verification=gqHgkOyPBANMIktwSO-L23jON_rj7qk1PJRfsYpfvmY

**Comment by IHIutch** [comment]
Just a note for my future self and maintainers. Search console is using a Domain property so the only way to verify is a TXT record. And as of writing DNS is managed in Netlify. 

@shannonmcharg still seems unable to see the verification, weirdly, but I can confirm we're seeing data 
![image](https://github.com/OpenMaine/maineballot/assets/20825047/652ed133-16c6-4b74-9804-e2a549a3cc0a)
