### ISSUE TITLE
Find and fix broken links on local election page

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#347]

**Comment by shannonmcharg** [comment]
[BadLinkChecker_www-maineballot-org-loca.xlsx](https://github.com/OpenMaine/maineballot/files/15406892/BadLinkChecker_www-maineballot-org-loca.xlsx)

**Comment by relspeedwagon** [comment]
Google sheets import of BadLinkChecker [spreadsheet](https://docs.google.com/spreadsheets/d/1lAfujDCzte4TTKVuhia6wI58z0fV6JXNw8j-wbbMSwI/edit?usp=sharing) to work on centrally :)

**Comment by relspeedwagon** [comment]
@shannonmcharg very last min., but finished checking all broken and unverified links in the copy of [BadLinkChecker spreadsheet](https://docs.google.com/spreadsheets/d/1lAfujDCzte4TTKVuhia6wI58z0fV6JXNw8j-wbbMSwI/edit?usp=sharing). Sheet should be ready to upload
