### ISSUE TITLE
Question 1: Political Action Committees

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#370]
# Question title
Super Political Action Committee (Super PAC) Contribution Limits

# Description (will display on homepage)
This measure would limit contributions to Super PACs.[5]

# The gist
This measure would limit contributions to Super PACs to $5,000 per year for individuals, businesses, unions, or other PACs.[2]

# Ballot question (exact text of the question)
"An Act to Limit Contributions to Political Action Committees That Make Independent Expenditures, Do you want to set a $5,000 limit for giving to political action committees that spend money independently to support or defeat candidates for office?"[5]

# Yes means
I am in favor of limited contributions to Super PACs to $5,000 per year.

# No means
I don't want to limit contributions to Super PACs.

# Tell me more
Super PACs are political action committees that make independent expenditures. They operate under different rules than regular political action committees and cannot give directly to political parties or politicians, but can independently campaign for or against candidates. Regular PACs, which can contribute directly to political parties or policitians,  have a $5,000 contribution limit and cannot accept contributions from businesses or unions.[2]

This question is a *citizen’s initiative*, which is a way for Mainers to propose new laws. In order to become a valid initiative, a petition supporting the initiative must collect over 60,000 signatures.

# Follow the money

It would cost $75,000 to update a campaign contribution database to impose the limit.[5]

# Pros
The primary arguments for this referendum are:
* It would reduce the influence businesses or people with a lot of money can have on elections.
* It would be a test case for other states to follow. [3]

# Cons
The primary arguments against this referendum are:
* Some consider limiting campaign contributions to be a limit on free speech.[5]
* If passed, the law is likely to be challenged in court. [3]

# Who cares [2]

Support 
* Citizens to End Super PACs
* Equal Citizens

Opposition
There is no registered opposition.

# Further reading
[Full text](https://www.maine.gov/sos/cec/elec/citizens/PAC%20Legislation.pdf)
[Ballotpedia article](https://ballotpedia.org/Maine_Question_1,_Limit_Contributions_to_Super_PACs_Initiative_(2024))
[Portland Press Herald Article](https://www.pressherald.com/2024/02/22/measure-to-limit-pac-contributions-could-be-headed-for-november-ballot/)

# References
_Put the number in brackets above to indicate a footnote to a reference._
1. Maine State Legislature. [PAC Legislation](https://www.maine.gov/sos/cec/elec/citizens/PAC%20Legislation.pdf). Accessed September 28, 2024.
2. Ballotpedia State Desk. [Maine Question 1, Limit Contributions to Super PACs Initiative (2024)](https://ballotpedia.org/Maine_Question_1,_Limit_Contributions_to_Super_PACs_Initiative_(2024)). Ballotpedia. Accessed September 28, 2024.
3. Russell, Eric. [Measure to limit PAC contributions in Maine could be headed for November ballot](https://www.pressherald.com/2024/02/22/measure-to-limit-pac-contributions-could-be-headed-for-november-ballot/). Portland Press Herald. Accessed September 28, 2024.
4. Russell, Eric. [Here’s the order of 5 Maine ballot questions, including PAC limits, state flag](https://www.pressherald.com/2024/07/30/ballot-question-order-announced-for-november-ballot/). Portland Press Herald. Accessed September 28, 2024.
5. Bellows, Shenna. [Maine Citizen’s Guide to the Referendum Election](https://www.maine.gov/sos/news/2024/2024%20Citizens%20Guide.pdf). Accessed September 28, 2024.

# Image
Use same image as this question: https://www.maineballot.org/november%202023%20election/q1_quasiborrowing/

# Tags
Citizen's Initiative, Super PAC, Campaign Contributions

# Election date
November 5, 2024

**Comment by shannonmcharg** [comment]
Content is drafted. @inomyabcs or @relspeedwagon Do one of you want to review?

**Comment by inomyabcs** [comment]
@shannonmcharg Reviewed. 👍
