### ISSUE TITLE
Question 2: R&D Bond

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#371]
# Question title
Research & Development Bond

# Description (will display on homepage)
This $25 million bond would fund research and development at the Maine Technology Institute.[3]

# The gist
This resolution would allow Maine to borrow $25 million for research and development at the Maine Technology Institute. The research would be in the fields of life sciences and biomedical technology, environmental and renewable energy technology, information technology, advanced technologies for forestry and agriculture, aquaculture and marine technology, composites and advanced materials and precision manufacturing. Maine Technology Institute would award the funds to Maine-based businesses through a competitive process and unlock matching funds.[^3]

# Ballot question (exact text of the question)
An Act to Authorize a General Fund Bond Issue for Research and Development and Commercialization, Do you favor a bond issue of $25,000,000 to provide funds, to be awarded through a competitive process and to leverage matching private and federal funds on at least a one-to-one basis, for research and development and commercialization for Maine-based public and private institutions in support of technological innovation in the targeted sectors of life sciences and biomedical technology, environmental and renewable energy technology, information technology, advanced technologies for forestry and agriculture, aquaculture and marine technology, composites and advanced materials and precision manufacturing?[^3]

# Yes means
I want to borrow $25 million for research and development.

# No means
I don't want to borrow $25 million for research and development.

# Tell me more
The [Maine Technology Institute](https://www.mainetechnology.org/) is a state-funded nonprofit that supports innovation.[^4]

Award of the funds would be competitive and contingent on a match from federal or private funds on at least a one-to-one basis.[^3]

This is a bond issue – if voters approve the bond, it means that the State of Maine is allowed to borrow money for the project described in the ballot question and has to pay it back over 10 years. [Learn more about how bonds work](https://www.maineballot.org/bonds).

# Follow the money
Principal: $25 million
Interest: $6.875 million
Total cost: $31.875 million[^3]

The money will be used to
* Award funds to Maine-based businesses for research and development.[3]
* Unlock federal or private matching funds.[3]

The money will be coming from
* $100 million bond issued by the state and paid back through the budget and taxes over 10 years.[3]
* Matching federal or private funds.[3]

# Pros
The primary arguments for this referendum are:
* Increased innovation in the state.

# Cons
The primary arguments against this referendum are:
* The funds may turn into commercial profit for the businesses who receive the funds.

# Who cares
Nobody has registered support or opposition to this bond.

# Further reading
[Full text](https://www.mainelegislature.org/legis/bills/getPDF.asp?paper=SP0197&item=1&snum=131)
[Ballotpedia article](https://ballotpedia.org/Maine_Question_2,_Science_and_Technology_Research_and_Commercialization_Bond_Issue_(2024))
[Portland Press Herald Article](https://www.pressherald.com/2024/09/17/question-2-asks-voters-to-support-25-million-research-and-development-bond/)

# References
_Put the number in brackets above to indicate a footnote to a reference._
[^1]: Maine State Legislature. [An Act to Authorize a General Fund Bond Issue for Research and Development and Commercialization](https://www.mainelegislature.org/legis/bills/getPDF.asp?paper=SP0197&item=1&snum=131). Accessed October 5, 2024.
[^2]: Ballotpedia State Desk. [Maine Question 2, Science and Technology Research and Commercialization Bond Issue (2024)](https://ballotpedia.org/Maine_Question_2,_Science_and_Technology_Research_and_Commercialization_Bond_Issue_(2024)). Ballotpedia. Accessed October 5, 2024.
[^3]: Bellows, Shenna. [Maine Citizen’s Guide to the Referendum Election](https://www.maine.gov/sos/news/2024/2024%20Citizens%20Guide.pdf). Accessed October 5, 2024.
[^4]: Ohm, Rachel. [Question 2 asks voters to support $25 million research-and-development bond](https://www.pressherald.com/2024/09/17/question-2-asks-voters-to-support-25-million-research-and-development-bond/). Portland Press Herald. Accessed October 5, 2024.

# Image
https://commons.wikimedia.org/wiki/File:Neutron_Research_facility_(5888575512).jpg

# Tags
Bond, Research and Development

# Election date
November 5, 2024

**Comment by shannonmcharg** [comment]
This one's ready to review.

**Comment by inomyabcs** [comment]
Reviewed.
