### ISSUE TITLE
Question 3: Historic Buildings Bond

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#372]
# Question title
Historic Buildings

# Description (will display on homepage)
This bond would allow the state to borrow $10 million to restore historic buildings owned by the government or nonprofits.[3]

# The gist
This resolution would allow the state to borrow $10 million to restore historic buildings owned by the government or nonprofits, if they can get at least 25% local matching funds.[^3]

# Ballot question (exact text of the question)
An Act to Authorize a General Fund Bond Issue to Restore Historic Community Buildings, Do you favor a $10,000,000 bond issue to restore historic buildings owned by governmental and nonprofit organizations, with funds being issued contingent on a 25% local match requirement from either private or nonprofit sources?[^3]

# Yes means
I want to borrow $10 million to restore historic buildings.

# No means
I don't want to borrow money to restore historic buildings.

# Tell me more
The Historic Preservation Commission will decide who gets grants. Only buildings that aren't already eligible for existing historic rehabilitation programs would be eligible.[^4]

This is a bond issue – if voters approve the bond, it means that the State of Maine is allowed to borrow money for the project described in the ballot question and has to pay it back over 10 years. [Learn more about how bonds work](https://www.maineballot.org/bonds).

# Follow the money
Principal: $10 million
Interest: $2.75 million
Total cost: $12.75 million[^3]

The money will be used to
* Restore historic buildings owned by the government or nonprofits.[3]

The money will be coming from
* $10 million bond issued by the state and paid back through the budget and taxes over 10 years.[^3]
* 25% matching funds from local organizations.[^3]

# Pros
The primary arguments for this referendum are:
* Historic buildings are expensive to restore and this would provide funds to governments and nonprofits who aren't likely to have funds themselves.
* This would unlock matching funds.

# Cons
The primary arguments against this referendum are:
* This would add to Maine's bond debt.

# Who cares
Nobody has registered support or opposition to this bond.

# Further reading
[Full text](https://legislature.maine.gov/legis/bills/getPDF.asp?paper=HP0568&item=1&snum=131)
[Ballotpedia article](https://ballotpedia.org/Maine_Question_3,_Historic_Community_Buildings_Bond_Issue_(2024))
[Press Herald Article](https://www.pressherald.com/2024/09/18/question-3-asks-voters-to-support-10-million-bond-for-historic-buildings/)

# References
_Put the number in brackets above to indicate a footnote to a reference._
[^1]: Maine State Legislature. [An Act to Authorize a General Fund Bond Issue to Restore Historic Community Buildings](https://legislature.maine.gov/legis/bills/getPDF.asp?paper=HP0568&item=1&snum=131). Accessed October 5, 2024.
[^2]: Ballotpedia State Desk. [Maine Question 3, Historic Community Buildings Bond Issue (2024)
](https://ballotpedia.org/Maine_Question_3,_Historic_Community_Buildings_Bond_Issue_(2024)). Ballotpedia. Accessed October 5, 2024.
[^3]: Bellows, Shenna. [Maine Citizen’s Guide to the Referendum Election](https://www.maine.gov/sos/news/2024/2024%20Citizens%20Guide.pdf). Accessed October 5, 2024.
[^4]: Billings, Randy. [Question 3 asks voters to support $10 million bond for historic buildings](https://www.pressherald.com/2024/09/18/question-3-asks-voters-to-support-10-million-bond-for-historic-buildings/)

# Image
https://commons.wikimedia.org/wiki/File:Lawerence_Public_Library,_Fairfield,_Maine.jpg

# Tags
Bond, Buildings

# Election date
November 5, 2024

**Comment by shannonmcharg** [comment]
This one is ready to review.

**Comment by inomyabcs** [comment]
Me reviewed.
