### ISSUE TITLE
Question 4: Trail Bond

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#373]
# Question title
Maine Trails Program

# Description (will display on homepage)
This bond would allow the state to borrow $30 million to fund the Maine Trails Program.

# The gist
This resolution would allow the state to borrow $30 million to fund the Maine Trails Program. This program would design, develop, and maintain trails in the state. It would unlock matching funds of at least $3 million.[^3]

# Ballot question (exact text of the question)
An Act to Authorize a General Fund Bond Issue to Promote the Design, Development and Maintenance of Trails for Outdoor Recreation and Active Transportation, Do you favor a $30,000,000 bond issue to invest in the design, development and maintenance for nonmotorized, motorized and multi-use trails statewide, to be matched by at least $3,000,000 in private and public contributions?[^3]

# Yes means
I want to borrow $30 million for trail improvements.

# No means
I don't want to borrow money for trails.

# Tell me more
* Eligible trails include public use trails that are nonmotorized (25% of funds, motorized (25% of funds), or multi-use (50% of funds) throughout the state.[^3]
* Grants will be awarded competitively to municipalities, the state government, or nonprofits.[^3]
* Sustainable, accessible, or inclusively designed projects will be prioritized.[^3]
* Projects must have 10% matching funds and be supported by a municipality, state agency, nonprofit, trail user program, business, or the public.[^3]

This is a bond issue – if voters approve the bond, it means that the State of Maine is allowed to borrow money for the project described in the ballot question and has to pay it back over 10 years. [Learn more about how bonds work](https://www.maineballot.org/bonds).

# Follow the money
Principal: $30 million
Interest: $8.25 million
Total cost: $38.25 million[^3]

The money will be used to
* Improve public trails in the state.

The money will be coming from
* $30million bond issued by the state and paid back through the budget and taxes over 10 years.[^3]
* 10% matching funds.[^3]

# Pros
The primary arguments for this referendum are:
* It would improve trails that are publicly available.
* More trail improvements are needed after the increasing number of storms.

# Cons
The primary arguments against this referendum are:
* It would increase the amount of bond debt the state has.

# Who cares

Support[2]
* L.L.Bean
* ATV Maine 
* Maine Municipal Association 
* Maine Snowmobile Association 
* Maine State Chamber of Commerce 
* Maine Tourism Association 
* Maine Youth Camping Association 

Opposition
*Nobody has registered opposition to this bond.

# Further reading
[Full text](https://legislature.maine.gov/legis/bills/getPDF.asp?paper=HP0728&item=1&snum=131)
[Ballotpedia article](https://ballotpedia.org/Maine_Question_4,_Development_and_Maintenance_of_Trails_Bond_Issue_(2024))
[Portland Press Hearald article](https://www.pressherald.com/2024/09/19/maine-will-consider-historic-30-million-bond-to-repair-and-restore-trails/)

# References
_Put the number in brackets above to indicate a footnote to a reference._
[^1]: Maine State Legislature. [An Act to Authorize a General Fund Bond Issue to Promote the Design, Development and Maintenance of Trails for Outdoor Recreation and Active Transportation](https://legislature.maine.gov/legis/bills/getPDF.asp?paper=HP0728&item=1&snum=131). Accessed [date].
[^2]: Ballotpedia State Desk. [Maine Question 4, Development and Maintenance of Trails Bond Issue (2024)
](https://ballotpedia.org/Maine_Question_4,_Development_and_Maintenance_of_Trails_Bond_Issue_(2024)). Ballotpedia. Accessed October 5, 2024.
[^3]: Bellows, Shenna. [Maine Citizen’s Guide to the Referendum Election](https://www.maine.gov/sos/news/2024/2024%20Citizens%20Guide.pdf). Accessed October 5, 2024.
[^4]: Ohn, Rachel. [Maine will consider historic $30 million bond to repair and restore trails
](https://www.pressherald.com/2024/09/19/maine-will-consider-historic-30-million-bond-to-repair-and-restore-trails/). Portland Press Herald. Accessed October 5, 2024.

# Image
https://commons.wikimedia.org/wiki/File:Crescent_Beach_State_Park_07.jpg

# Tags
Bond, Trails
# Election date
November 5, 2024

**Comment by shannonmcharg** [comment]
This one is ready to review.

**Comment by inomyabcs** [comment]
Let me see if I can run down a number on the expected return or the current return of tourism dollars from trails.

**Comment by inomyabcs** [comment]
I don't have great numbers. There is a consultant report on the impact on the [Eastern Maine Trail](https://www.maine.gov/mdot/ofps/docs/mdrcc/Camoin%20Associates%20Report%20-%20Economic%20Impact%20of%20ET%20-%20SMPDC.pdf) if there was a million dollar infusion in the system. So just ignore my musings. All set on this one I think.
