### ISSUE TITLE
Question 5: State Flag

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#374]
# Question title
State Flag

# Description (will display on homepage)
This measure would restore the old pine tree design for the state flag.

# The gist
This measure would restore a [version of the old Pine Tree Flag](https://www.maine.gov/sos/news/2024/Winner%20-%20Maine%20State%20Flag%20Redesign%20Contest.pdf) that was selected as part of a [contest](https://www.maine.gov/sos/news/2024/FlagContestWinningDesignUnveiled.html).[4]

# Ballot question (exact text of the question)
"An Act to Restore the Former State of Maine Flag, Do you favor making the former state flag, replaced as the official flag of the State in 1909 and commonly known as the Pine Tree Flag, the official flag of the State?"[4]

# Yes means
I want to change to the Pine Tree Flag.

# No means
I want to keep the current flag.

# Tell me more
People have been flying unofficial versions of the Pine Tree Flag for years. This would make it the official flag. In 2023, the state legislature passed legilsation allowing this referendum question to see whether citizens want the new flag.[6]

# Follow the money

The costs to change flags would be absorbed into existing budgets.[4]

# Pros
The primary arguments for this referendum are:
* The Pine Tree Flag is simpler and more recognizable than the current flag.
* Maine is the pine tree state, so the new flag would reflect that.

# Cons
The primary arguments against this referendum are:
* Some think the Pine Tree Flag design looks amateurish.
* The new design doesn't include as many aspects of Maine's history, such as farming and fishing, as the old one does. [5]

# Who cares
There is no registered support or opposition to this measure.

# Further reading
[Full text](https://www.mainelegislature.org/legis/bills/getPDF.asp?paper=HP0054&item=1&snum=131)
[Ballotpedia article](https://ballotpedia.org/Maine_Question_5,_State_Flag_Referendum_(2024))
[Portland Press Herald Article](https://www.pressherald.com/2024/09/13/at-long-last-mainers-could-vote-for-a-new-state-flag-heres-everything-you-need-to-know/)

# References
_Put the number in brackets above to indicate a footnote to a reference._
1. Maine State Legislature. [An Act to Restore the Former State of Maine Flag](https://www.mainelegislature.org/legis/bills/getPDF.asp?paper=HP0054&item=1&snum=131). Accessed September 29, 2024.
2. Ballotpedia State Desk. [Maine Question 5, State Flag Referendum (2024)
](https://ballotpedia.org/Maine_Question_5,_State_Flag_Referendum_(2024)). Ballotpedia. Accessed September 15, 2024.
3. Maine Secretary of State. [Flag contest winning design unveiled](https://www.maine.gov/sos/news/2024/FlagContestWinningDesignUnveiled.html). Accessed September 29, 2024.
4. Bellows, Shenna. [Maine Citizen’s Guide to the Referendum Election](https://www.maine.gov/sos/news/2024/2024%20Citizens%20Guide.pdf). Accessed September 29, 2024.
5. Bouchard, Kelley. [Unfurling the facts in the 1901 Maine state flag debate](https://www.pressherald.com/2023/08/13/unfurling-the-facts-in-the-1901-maine-state-flag-debate/). Portland Press Herald. Accessed September 29, 2024.
6. Ohm, Rachel. [At long last, Mainers could vote for a new state flag. Here’s everything you need to know.
](https://www.pressherald.com/2024/09/13/at-long-last-mainers-could-vote-for-a-new-state-flag-heres-everything-you-need-to-know/). Portland Press Herald. Accessed September 29, 2024.

# Image
![image](https://github.com/user-attachments/assets/63241d24-12c6-4992-9e8d-9f1dc82f027f)
Accessed: https://www.maine.gov/sos/news/2024/Winner%20-%20Maine%20State%20Flag%20Redesign%20Contest.pdf

# Tags

# Election date

**Comment by shannonmcharg** [comment]
This one is drafted. @inomyabcs @relspeedwagon Either of you want to review?

**Comment by inomyabcs** [comment]
@shannonmcharg Looks good.
