### ISSUE TITLE
Check for broken links on local elections page

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#375]

**Comment by rentry** [comment]
Initial check below. I'll try to track down valid links for them.

404 | Not Found | https://www.townofgreene.net/elections
-- | -- | --
404 | Not Found | https://www.freeportmaine.com/town-clerk/pages/election-services
404 | Not Found | https://www.franklincountymaine.org/members/profile/town-of-carthage
0 | Empty Response or No Access-Control-Allow-Origin | http://www.penobscot-maine.com/
404 | Not Found | http://www.augustamaine.gov/businesses/city_government/elections.php
404 | Not Found | https://china.govoffice.com/elections
0 | Empty Response or No Access-Control-Allow-Origin | http://www.manchester.govoffice2.com/
0 | Empty Response or No Access-Control-Allow-Origin | https://romemaine.com/departments/clerk/
404 | Not Found | http://www.waterville-me.gov/clerk/general-election-information-2/ -> https://www.waterville-me.gov/clerk/general-election-information-2/
404 | Not Found | https://www.camdenmaine.gov/town_clerk/elections___voter_registration.php
404 | Not Found | https://www.nobleboro.maine.gov/index.asp?SEC=0A6C6CD7-512A-43E9-B9C2-DD879B3D7ED5
504 | Gateway Timeout | https://uptonmaine.org/
404 | Not Found | https://www.westparisme.com/index.asp?SEC=19147DB6-D2B4-46FE-8C61-8385CF9880BD -> https://westparisme.com/index.asp?SEC=19147DB6-D2B4-46FE-8C61-8385CF9880BD
404 | Not Found | https://sites.google.com/site/townofetna -> https://sites.google.com/site/sites/system/errors/WebspaceNotFound?path=%2Ftownofetna
404 | Not Found | https://newburghmaine.ipage.com/
0 | Empty Response or No Access-Control-Allow-Origin | https://www.seboeisplantationme.com/
504 | Gateway Timeout | http://bowerbank.trcmaine.org/
504 | Gateway Timeout | http://brownville.trcmaine.org/
404 | Not Found | https://greenvilleme.com/town-office/voter-registration-election-info/
504 | Gateway Timeout | http://medford.trcmaine.org/
404 | Not Found | http://www.arrowsic.org/clerk_page.html#elections -> https://www.arrowsic.org/clerk_page.html
403 | Forbidden | https://www.bowdoinham.com/elections
404 | Not Found | http://www.fairfieldme.com/town/pages/voter-registration
404 | Not Found | https://www.pittsfield.org/newselections
0 | Empty Response or No Access-Control-Allow-Origin | https://townofmilbridge.webs.com/
0 | Empty Response or No Access-Control-Allow-Origin | http://www.whitneyvilleme.com/
404 | Not Found | http://www.actonmaine.org/index.cfm
404 | Not Found | https://www.eliotmaine.org/election-information-november-2-2021
404 | Not Found | https://www.kennebunkportme.gov/town-clerk/pages/elections-and-voting
404 | Not Found | https://www.googletagmanager.com -> https://www.googletagmanager.com/
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=allagash&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=blaine&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=cary&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=caswell&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=crystal&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=cyr+plantation&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=dyer+brook&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=garfield+plantation&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=glenwood+plantation&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=hamlin&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=hammond&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=haynesville&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=hodgdon&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=linneus&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=macwahoc&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=masardis&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=monticello&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=canada&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=sweden&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=oxbow&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=perham&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=sherman&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=john&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=stockholm&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=westfield&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=westmanland&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=winterville&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=avon&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=rangeley&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=sandy&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=aurora&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=sorrento&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=waltham&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=lincoln&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=edinburg&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=lakeville&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=maxfield&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=webster&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=atkinson&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=brighton&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=dennistown&amp
500 | Internal Server Error | https://www.facebook.com/permalink.php?id=201376573099&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=moose&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=ridge&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=ripley&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=beals&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=codyville&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=crawford&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=deblois&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=dennysville&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=roque&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=topsfield&amp
500 | Internal Server Error | https://www.maine.gov/tools/whatsnew/index.php?k=vanceboro&amp
0 | Empty Response or No Access-Control-Allow-Origin | http://www.whitneyvilleme.com

404	Not Found	https://www.townofgreene.net/elections
404	Not Found	https://www.freeportmaine.com/town-clerk/pages/election-services
404	Not Found	https://www.franklincountymaine.org/members/profile/town-of-carthage
0	Empty Response or No Access-Control-Allow-Origin	http://www.penobscot-maine.com/
404	Not Found	http://www.augustamaine.gov/businesses/city_government/elections.php
404	Not Found	https://china.govoffice.com/elections
0	Empty Response or No Access-Control-Allow-Origin	http://www.manchester.govoffice2.com/
0	Empty Response or No Access-Control-Allow-Origin	https://romemaine.com/departments/clerk/
404	Not Found	http://www.waterville-me.gov/clerk/general-election-information-2/ -> https://www.waterville-me.gov/clerk/general-election-information-2/
404	Not Found	https://www.camdenmaine.gov/town_clerk/elections___voter_registration.php
404	Not Found	https://www.nobleboro.maine.gov/index.asp?SEC=0A6C6CD7-512A-43E9-B9C2-DD879B3D7ED5
504	Gateway Timeout	https://uptonmaine.org/
404	Not Found	https://www.westparisme.com/index.asp?SEC=19147DB6-D2B4-46FE-8C61-8385CF9880BD -> https://westparisme.com/index.asp?SEC=19147DB6-D2B4-46FE-8C61-8385CF9880BD
404	Not Found	https://sites.google.com/site/townofetna -> https://sites.google.com/site/sites/system/errors/WebspaceNotFound?path=%2Ftownofetna
404	Not Found	https://newburghmaine.ipage.com/
0	Empty Response or No Access-Control-Allow-Origin	https://www.seboeisplantationme.com/
504	Gateway Timeout	http://bowerbank.trcmaine.org/
504	Gateway Timeout	http://brownville.trcmaine.org/
404	Not Found	https://greenvilleme.com/town-office/voter-registration-election-info/
504	Gateway Timeout	http://medford.trcmaine.org/
404	Not Found	http://www.arrowsic.org/clerk_page.html#elections -> https://www.arrowsic.org/clerk_page.html
403	Forbidden	https://www.bowdoinham.com/elections
404	Not Found	http://www.fairfieldme.com/town/pages/voter-registration
404	Not Found	https://www.pittsfield.org/newselections
0	Empty Response or No Access-Control-Allow-Origin	https://townofmilbridge.webs.com/
0	Empty Response or No Access-Control-Allow-Origin	http://www.whitneyvilleme.com/
404	Not Found	http://www.actonmaine.org/index.cfm
404	Not Found	https://www.eliotmaine.org/election-information-november-2-2021
404	Not Found	https://www.kennebunkportme.gov/town-clerk/pages/elections-and-voting
404	Not Found	https://www.googletagmanager.com -> https://www.googletagmanager.com/
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=allagash&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=blaine&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=cary&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=caswell&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=crystal&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=cyr+plantation&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=dyer+brook&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=garfield+plantation&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=glenwood+plantation&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=hamlin&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=hammond&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=haynesville&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=hodgdon&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=linneus&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=macwahoc&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=masardis&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=monticello&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=canada&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=sweden&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=oxbow&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=perham&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=sherman&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=john&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=stockholm&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=westfield&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=westmanland&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=winterville&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=avon&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=rangeley&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=sandy&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=aurora&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=sorrento&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=waltham&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=lincoln&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=edinburg&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=lakeville&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=maxfield&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=webster&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=atkinson&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=brighton&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=dennistown&amp
500	Internal Server Error	https://www.facebook.com/permalink.php?id=201376573099&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=moose&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=ridge&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=ripley&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=beals&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=codyville&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=crawford&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=deblois&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=dennysville&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=roque&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=topsfield&amp
500	Internal Server Error	https://www.maine.gov/tools/whatsnew/index.php?k=vanceboro&amp
0	Empty Response or No Access-Control-Allow-Origin	http://www.whitneyvilleme.com/

**Comment by rentry** [comment]
@shannonmcharg here's a start...

Code | Status | Broken link | Alternative
-- | -- | -- | --
404 | Not Found | https://www.townofgreene.net/elections | ?
404 | Not Found | https://www.freeportmaine.com/town-clerk/pages/election-services | https://www.freeportmaine.com/231/Elections-Voter-Registration-Services
404 | Not Found | https://www.franklincountymaine.org/members/profile/town-of-carthage | ?
0 | Empty Response or No Access-Control-Allow-Origin | http://www.penobscot-maine.com/ | https://penobscotmaine.org/
404 | Not Found | http://www.augustamaine.gov/businesses/city_government/elections.php | https://www.augustamaine.gov/elections
404 | Not Found | https://china.govoffice.com/elections | https://chinamaine.org/departments/administration/town-clerk/elections
0 | Empty Response or No Access-Control-Allow-Origin | http://www.manchester.govoffice2.com/ | https://www.manchesterme.org/town-clerk
0 | Empty Response or No Access-Control-Allow-Origin | https://romemaine.com/departments/clerk/ | https://www.romemaine.com/town-clerk-registrar
404 | Not Found | http://www.waterville-me.gov/clerk/general-election-information-2/ | https://www.waterville-me.gov/192/General-Election-Information
404 | Not Found | https://www.camdenmaine.gov/town_clerk/elections___voter_registration.php | https://www.camdenmaine.gov/departments/town_clerk/departments/town_clerk/index.php
404 | Not Found | https://www.nobleboro.maine.gov/index.asp?SEC=0A6C6CD7-512A-43E9-B9C2-DD879B3D7ED5 | https://www.nobleboro.maine.gov/index.asp?SEC=67EBFAF5-F8EA-425F-B95E-A9E91456E085
404 | Not Found | https://westparisme.com/index.asp?SEC=19147DB6-D2B4-46FE-8C61-8385CF9880BD | https://westparisme.com/pages/elections
404 | Not Found | https://sites.google.com/site/townofetna | https://www.townofetna.com/
404 | Not Found | https://newburghmaine.ipage.com/ | https://www.townofnewburghmaine.com/
0 | Empty Response or No Access-Control-Allow-Origin | https://www.seboeisplantationme.com/ | ?
504 | Gateway Timeout | http://bowerbank.trcmaine.org/ | ?
504 | Gateway Timeout | http://brownville.trcmaine.org/ | https://www.brownville.org
404 | Not Found | https://greenvilleme.com/town-office/voter-registration-election-info/ | https://greenvilleme.gov/town-office/voter-registration-election-info/
504 | Gateway Timeout | http://medford.trcmaine.org/ | http://townofmedfordmaine.com/index.html
404 | Not Found | http://www.arrowsic.org/clerk_page.html#elections | https://www.arrowsic.org/elections.html
404 | Not Found | http://www.fairfieldme.com/town/pages/voter-registration | http://www.fairfieldme.com/town/pages/elections-and-voting
404 | Not Found | https://www.pittsfield.org/newselections | https://www.pittsfield.org/govtdepartmentsclerk
0 | Empty Response or No Access-Control-Allow-Origin | https://townofmilbridge.webs.com/ | ?
0 | Empty Response or No Access-Control-Allow-Origin | http://www.whitneyvilleme.com/ | ?
404 | Not Found | http://www.actonmaine.org/index.cfm | https://www.actonmaine.org/
404 | Not Found | https://www.eliotmaine.org/election-information-november-2-2021 | https://www.eliotmaine.org/404/Elections
404 | Not Found | https://www.kennebunkportme.gov/town-clerk/pages/elections-and-voting | https://www.kennebunkportme.gov/departments/town_clerk/elections_and_voting.php

**Comment by shannonmcharg** [comment]
This is the spreadsheet the links need to be updated in. https://docs.google.com/spreadsheets/d/1dk58MD0qBAM37BDOZwKIz10hp5AARAIX8u_qvuDnYaI/edit?gid=0#gid=0

**Comment by shannonmcharg** [comment]
@rentry I fixed all the ones you found in the Google sheet and found a few more. I started replacing all the ones from the maine.gov contact info ool, but it appears I have them right in the Google Sheet and it's cutting them off at the first ampersand. They're correct in the .csv. Is there something we can do to prevent the cutting off on the site?

**Comment by shannonmcharg** [comment]
The maine.gov links are working on the site, they're just cutting off in the broken link checker.

**Comment by rentry** [comment]
Yes, I noticed that with maine.gov, so omitted them from the second comment.

Fixed via #376
