### ISSUE TITLE
Optimize logo for social sharing

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#49]
When I post to Facebook, the logo gets cutoff.  Is there something we can control to prevent that?
![0196115C-C442-46B1-B3B7-94C4D69B8B73](https://user-images.githubusercontent.com/12865238/66648905-c6bae800-ebfa-11e9-90a3-f97c3421b3b0.png)

**Comment by curtisk** [comment]
going to have a pull request coming that should address this

**Comment by curtisk** [comment]
hmmm Twitter isn't playing nice which is odd, looks good sharing on FB, snapchat, Messenger, Messages(IOS), etc. looking into it

**Comment by curtisk** [comment]
actually, just ran it through the twitter card validator and its good now (?), if any issues arise we can re-open

**Comment by shannonmcharg** [comment]
It's pulling through to Twitter after refreshing. 
![image](https://user-images.githubusercontent.com/12865238/66672946-8759bf00-ec2d-11e9-8be0-52ad34e9eaf8.png)
