### ISSUE TITLE
Set up Google Analytics to track outbound links

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#54]
So we can track which local websites people are going to.

**Comment by curtisk** [comment]
got it

**Comment by curtisk** [comment]
Working as expected on the site now, closing issue

Side discussion on capturing search progression I will look at some more, but can likely handle solely on the Tag Manager side

**Comment by shannonmcharg** [comment]
This is working!
![image](https://user-images.githubusercontent.com/12865238/67823262-b7f88000-fa98-11e9-8fff-8f1fdd8f4e51.png)
