### ISSUE TITLE
Add unorganized townships to the town list

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#56]
A list of them is here.
https://www.maine.gov/revenue/propertytax/unorganizedterritory/ut_map_ref.pdf

The ones in Penobscot, Sagadahoc, and Oxford counties are already added.

**Comment by shannonmcharg** [comment]
Website for Hancock County unorganized territories: https://co.hancock.me.us/site/index.php/county-departments/unorganized-territory

**Comment by shannonmcharg** [comment]
Website for Aroostook County unorganized territories: https://www.aroostook.me.us/departments/public-works.html

**Comment by elburnett** [comment]
@shannonmcharg would this be a good first project for someone to pitch in on?

**Comment by shannonmcharg** [comment]
@elburnett  I think so.

**Comment by shannonmcharg** [comment]
I think this is low value add.
