### ISSUE TITLE
WCAG2 tweaks

### ISSUE THREAD

**Issue by curtisk** [OpenMaine/maineballot#66]
Since I deal with this a lot with day job, took a look at Accessibility score and any flagged issues based on WCAG2.0 at least...will work on a few small changes to help in this area. One major hit is with the lighter grey font color in top menu for instance, they like to have a certain degree of contrast to help with those with vision impairment, so that means that grey may just need to be a little darker throughout, some items on site could use wai-aria labels etc.

I'll self assign but if anyone else wants to chip in feel free

**Comment by curtisk** [comment]
Still a few places with structure issues, H1's with empty content for example, will chip away

**Comment by curtisk** [comment]
So, as I look into this more, the correct course of action is to actually open an issue over at Minimal Mistakes, since I'm finding myself messing with the core SCSS/CSS from that set of templates....I can certainly tweak OUR copy of it, but if we ever update it from the source project, we'd have to do it all over again. Don't know if this should close at this point.

**Comment by shannonmcharg** [comment]
Do we think we'll need to update from the source project?  I don't know how that normally works, since I have ever forked from another project before.

**Comment by curtisk** [comment]
Gonna look at latest version of site, I think we're alot better, bottom footer probably still needs the font to be darker
