### ISSUE TITLE
Figure out how to archive ballot content for local elections

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#79]
We're currently displaying what's on the ballot for local elections in a table column.  We need a way to archive this for future reference.  We should do it before the June election when we'll have new content for the column.

**Comment by curtisk** [comment]
Talking about this info? 
![image](https://user-images.githubusercontent.com/2028068/74357059-53360c80-4d8d-11ea-98a4-67ee1fbf3cfb.png)

**Comment by shannonmcharg** [comment]
@curtisk Yes.  I'd be nice to somehow archive that, so we can go back and see which localities voted on which things, but I don't think it should be cluttering up the main page where people are looking for info on the current election.

**Comment by rentry** [comment]
Partially fixed by #95. Closing, with anticipation of enhancements.
