### ISSUE TITLE
Review font on mobile

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#9]
Google Search Console flagged the site as having issues because of font size on mobile.  They, however, provided no details.

**Comment by shannonmcharg** [comment]
Google flagged this again, but now they'll tell me what pages it's on. Not sure why it's only flagging the one page, since it uses a template...
![image](https://user-images.githubusercontent.com/12865238/70354086-c88cda80-183c-11ea-9991-8cb8082ac9d3.png)

![image](https://user-images.githubusercontent.com/12865238/70354126-de9a9b00-183c-11ea-9856-d435f21b7d6a.png)

**Comment by curtisk** [comment]
can you check again? I've been trying to determine what its complaining about and not seeing it, especially on that one archived question

**Comment by shannonmcharg** [comment]
I did get another email from them recently:
![image](https://user-images.githubusercontent.com/12865238/74361121-4f59b880-4d94-11ea-90e7-3306ebfa5eab.png)

**Comment by shannonmcharg** [comment]
But it doesn't want to tell me which page is the 1 affected page.

**Comment by shannonmcharg** [comment]
![image](https://user-images.githubusercontent.com/12865238/74361772-7cf33180-4d95-11ea-8468-fb56480861d7.png)

**Comment by shannonmcharg** [comment]
I'm going to close this and reopen if we can ever figure out which page it's on.
